DiceDB/dice

core/eval.go

Enables AOF operation through a background thread. Solves the Issue https://github.com/DiceDB/dice/issues/1

Background thread for BGREWRITEAOF

---

core/eval.go

For issue - https://github.com/DiceDB/dice/issues/16 added inline documentation.

Added inline documentation for BGREWRITEAOF

---

README.md

Fixed spelling issues in the README.md

Fixing contribute typo

---

core/eval.go

Added inline-documentation for funcs in eval.go

---

core/eval.go
core/object.go
core/queueint_test.go
core/queueref.go
core/queueref_test.go
core/resp.go

QueueRef implementation

---

core/eval.go
core/executor.go
core/executor_test.go
core/io_test.go
core/resp.go
core/store.go
main.go
tests/qwatch_test.go
tests/set_test.go

* The QWATCH E2E test seems flaky and will be fixed later.

Enables end to end QWATCH flow using DSQL + Improved test coverage.

---

.github/workflows/tests.yml
core/bloom_test.go

Add CI testing as part of push to master branch and PRs. Avoid accidental bad code merges

---

core/aof.go
core/dencoding/int.go
core/eval.go
core/queueint.go
core/resp.go
server/async_tcp.go

Clean sweep to fix all existing lint errors. Please merge after linter PR is merged (which will help catch any errors in this change). Has been tested in my fork meanwhile -
github.com/DiceDB/dice/pull/136
Current status -
List of lint errors fixed -

Clean sweep to fix all existing lint errors. For best experience please merge this after linter PR (#136) is merged.

---

tests/qwatch_test.go

Improved the integration test for QWATCH using proper assertions and better test cases to validate all edge case behaviors.

Improve QWATCH test

---

.github/workflows/tests.yml

Runs integration tests as a part of the CI.

Run integration tests on GitHub Actions

---

README.md
core/bytearray.go
core/bytearray_test.go

Added very basic byte array, with 
SETBIT, GETBIT and BITCOUNT support to prove functional capabilities.
Please share feedback.

#142 - Support for byte array

---

core/bytearray_test.go

#142 :missed adding benchamrk for bitcount for byte array. fixed

#142 :missed adding benchamrk for bitcount for byte array. fixed

---

core/aof.go
core/aof_test.go
core/eval.go

Issue: https://github.com/DiceDB/dice/issues/90
- Fix AOF file permissions
- Rewrote AOF writes using bufio for cross OS support
- Added fsync after the file write is completed
- Added test cases for AOF
- Ran unittest cases for AOF
- Manual testing on dev environment

Issue #90 Fix AOF file permissions

---

core/type_string_test.go

Unit test of core Deducetypencoding method

feat:add deduceTypeEncoding unit test

---

core/dencoding/int.go
core/dencoding/int_test.go

#223: Added sync.Pool for thread safety

---

.air.toml
README.md

Via air package hot reload can be possible on different files such as .go, .tpl, .tmpl, .yaml.
Air package can be installed in many different ways mentioned here: https://github.com/air-verse/air
Best way if you're on go 1.22+
`go install github.com/air-verse/air@latest`
Or 
```
curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
```

#233: Support for live reload

---

core/commands.go
core/eval.go
core/eval_test.go
core/expire.go
core/expire_test.go

feat:add persist command 
issue #258

feat:add persist cmd

---

core/commands.go
core/eval.go
tests/decr_test.go

Close #279.
This PR is going to support command DECR.

Add support for command DECR

---

core/commands.go
core/eval.go
core/store.go
tests/exists_test.go

Added new command 'EXISTS' and Store function 'GetNoTouch' for getting key without updating last accessed time for that record
This is implemented as per the Redis EXISTS command.
Added integration tests in test folder.

New feature: EXISTS k1, k2..Kn

---

core/commands.go
tests/command_getkeys_test.go

Fixes: Issue #271 
Added `KeySpec.LastKey = -1` to support `COMMAND getkeys MSET`

#271: fixed MsetCmdMeta to support COMMAND getkeys

---

core/commands.go
core/eval.go
tests/decr_test.go

closes #291.
Also did changes (Added test-case for string)  requested in this closed [PR](https://github.com/DiceDB/dice/pull/291).

Add  support for DECRBY

---

core/stackref_test.go

#185: Added test cases for expired keys in StackRef.Pop() method

---

core/commands.go
core/eval.go
core/store.go
tests/command_rename_test.go

Added support for Rename Command #253

#253: added RENAME Command

---

core/eviction.go
core/executor.go
core/expire.go
core/locks.go
core/queueref.go
core/stackref.go
core/store.go

This PR introduces a new functional locking strategy to our codebase, improving the consistency and flexibility of our synchronization mechanisms. It also enforces ordered lock acquisition which helps reduce chances of deadlocks due to badly ordered lock acquisition.
* Introduced a new locks.go file implementing the functional locking strategy.
* Refactored existing instances of direct mutex locking instances to use the withLocks utility.
* Refactored store.go to reduce duplication and reduce chances of errors.
* Updated helper functions to be compatible with the new locking strategy.
* All existing unit and integration tests are passing.

Implement functional locking strategy

---

core/commands.go
core/eval.go
core/store.go
tests/getdel_test.go

Added support for GetDel command.
https://github.com/DiceDB/dice/issues/274

#274: Added support for GETDEL command.

---

tests/del_test.go

This PR aims to improve test coverage by adding test cases for `DEL` command
Issue: https://github.com/DiceDB/dice/issues/73

#73: testcase for DEL command

---

CONTRIBUTING.md

There's a broken link for the golangci . Fixed it

Update broken links for golangci

---

core/commands.go
core/eval.go
tests/ttl_pttl_test.go

Added support for PTTL command as per Redis and similar to TTL command in Dice. 
Added tests for both TTL and PTTL command in tests folder
* Design document, if any.
* Information on any implementation choices that were made.
* Evidence of sufficient testing. You ``MUST`` indicate the tests done, either manually or automated.
Added new tests for PTTL and TTL.

Added support for PTTL command

---

main.go

Looked through main file and fixed a basic grammatical typo.

fixed minor typo in main.go file

---

core/queueref_test.go

Fix incorrect benchmark iteration count.
- Added scenarios to benchmark with different non-expired keys count.
[benchmark_results.txt](https://github.com/user-attachments/files/16644588/benchmark_results.txt)
Issues : #184

#184 : Fixed incorrect benchmark iterations for QueueRef

---

core/eval.go
core/eval_test.go

PR to address: [issue](https://github.com/DiceDB/dice/issues/346)
Changes:
* Use `KeyspaceStat` to improve performance
* Fixed unit test for `DBSIZE` store API

#346: Uses KeySpaceStat for evaluating DBSIZE to improve performance.

---

core/eval.go
core/eval_test.go
tests/expire_test.go
tests/expiretime_test.go

Issue: https://github.com/DiceDB/dice/issues/361

#361: Added unit test and integration test for EXPIRE, EXPIRETIME commands

---

core/eval.go
core/object.go
core/type_string.go
core/type_string_test.go
tests/json_test.go
tests/mget_test.go

* Fixes the type deduction logic to correspond to the new integer handling logic where we don't store integers as strings.
* Also includes some misc test fixes.

Type Deduction logic and related fixes

---

core/cmd.go
server/sync_tcp.go
server/utils/ids.go

Temporarily assigning ID to every incoming command

---

core/commands.go
core/eval.go
internal/constants/constants.go

closes https://github.com/DiceDB/dice/issues/389
Redis FLUSHDB https://redis.io/docs/latest/commands/flushdb/
TODO: add unit tests and integration tests

Added support for FLUSHDB command

---

core/eval.go
internal/constants/constants.go
server/utils/time.go
tests/expire_test.go
tests/expireat_test.go

https://github.com/DiceDB/dice/issues/355

#355: FEAT: Added support for additional options in EXPIRE and EXPIREAT.

---

config/main.go
core/bitpos.go
core/eval.go
main.go
server/async_tcp.go
tests/setup.go
testutils/json.go

This PR refactors the AsyncServer implementation to improve modularity, error handling, and overall code structure. 
1. Introduced a new `AsyncServer` struct to encapsulate server state and behavior.
2. Moved server configuration options to `config/main.go`.
3. Improved error handling throughout the server.
4. Improved shutdown handling.

Reorganize async server code

---

core/bitpos.go
core/bytearray.go
core/eval.go
tests/bit_operation_test.go

closes #386.
- Added Encoding for byteArray in evalGET
- Fixed SETBIT for string and integer
- Added tests for above

#386 Fix SETBIT command  for encoding

---

config/main.go
core/auth/session.go
core/auth/session_test.go
core/bitpos.go
core/cmd/cmds.go
core/comm.go
core/comm/client.go
core/commands.go
core/diceerrors/diceerrors.go
core/eval.go
core/eval_test.go
core/events.go
core/object.go
core/ops/store_op.go
core/query_watcher.go
core/shard_manager.go
core/shard_thread.go
core/typeencoding.go
main.go
server/async_tcp.go
server/sync_tcp.go
tests/main_test.go
tests/setup.go

This PR introduces ShardThread and ShardManager into Dice.

Adds ShardThread and ShardManager

---

core/eval.go

Hi team,
-- Addresses #444 
I have migrated the set data structure and related commands to use swisstable instead of builtin map. I am not familiar with the usage, especially when iterating over the set, so I would like a quick review. 
This will help us in staying up to date with the design specs and decisions for performance.
cc - @JyotinderSingh 
All tests are passing.
Regards,
Apoorv

#444: Migrated from built-in go map to swissTable for set data as per #433

---

core/eval.go

Hi Team,
This PR reverts the set data structure to go's built-in map type. 
All tests pass.
Regards,
Apoorv

Reverted set data structure to map

---

internal/store/typeencoding.go

optimized type Error Return
close issus:#475

fix:optimized type Error Return

---

internal/querywatcher/query_watcher.go
internal/sql/constants.go
internal/sql/executor.go
internal/store/store.go

This change introduces optimizations to the query execution process, particularly focusing on handling JSON data efficiently:
1. A caching mechanism for JSONPath expressions
2. Enhancing the sorting logic to handle different data types and `nil` values correctly
- Reduces overhead from repeatedly parsing the same JSONPath expressions during query execution.
- Added a `jsonPathCache` to cache parsed JSONPath expressions.
- In `retrieveValueFromJSON`, before parsing a JSONPath, check the cache to see if it's already parsed.
- Improves the efficiency of sorting query results.
- Introduced a new struct `QueryResultRowWithOrder` to hold each row along with its precomputed order-by value and type. Facilitates efficient sorting without recalculating order-by values.
- Modified `ExecuteQuery` to: …

SQL Executor Performance Improvements

---

integration_tests/commands/select_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

#569: cmd: add SELECT cmd

---

integration_tests/commands/deque_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Closes https://github.com/DiceDB/dice/issues/572
1. Added support for LLEN
2. Added unit tests and integration tests
All tests passed.

#572: Added support for LLEN command

---

go.mod
go.sum
integration_tests/commands/json_test.go
internal/eval/commands.go
internal/eval/constants.go
internal/eval/eval.go
internal/eval/eval_test.go

PR addresses #496 
The changes that are included in the PR.
Added support for JSON.NUMINCRBY. added unit tests and integration tests
All tests passed.
Design Considerations:
Using expr.MustModify() function we should be able to modify the json as per custom requirements. If the changes look good, this PR can be used as a reference for other issues containing logic to update the path such as json.toggle. 
cc:- @JyotinderSingh , @jujiale

#496 Feature `JSON.NUMINCRBY`

---

integration_tests/commands/json_arrpop_test.go
internal/clientio/resp.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Closes #489 
Implemented JSON.ARRPOP command.

Added JSON.ARRPOP command

---

internal/eval/eval.go
internal/eval/eval_amd64.go
internal/eval/eval_arm64.go

The current version of the EvalBGREWRITEAOF method does not support arm64. Add support for arm64.

Add support for arm64

---

integration_tests/commands/incr_test.go

`Image Attached`
_This PR significantly expands the test coverage for the INCR command. I've added several new test cases to ensure robustness and correct behavior under various scenarios._
**New test cases include:**
1. Increment to and from max int64
Tests behavior at the upper limit of int64
Ensures proper error handling when exceeding the limit
2. Increment from min int64
Verifies correct incrementing from the lower bound of int64
3. Increment non-integer values
Checks error handling when attempting to increment floats, strings, and booleans
4. Increment non-existent key
Ensures proper initialization and incrementing of previously non-existent keys
5. Increment string representing integers
Tests correct handling of string-stored integer values
6. Increment with expiry
Verifies …

ENH: Expand INCR command test suite with comprehensive edge cases

---

config/config.go
internal/auth/session.go
internal/auth/session_test.go
internal/eval/eval.go
internal/server/server.go
internal/store/lfu_eviction_test.go
main.go

1. merges flag value to the global config object in order to prioritize `-requirepass` flag
2. shows warning if dice starts without password
3. uses `config.DiceConfig.Auth.UserName` as a default user

#609 fix: auth vulnerability

---

internal/clientio/io.go

Fixes: #225 
As per the issue description, the following failure scenarios have been added 
- Timeout: Check if net.Error and checking if it's a timeout.
- Connection closed locally: Detect by checking for syscall.EBADF or os.ErrClosed.
- Connection reset: Detect by checking for syscall.ECONNRESET
Note - It is mentioned in the issue to cover similar failure scenarios for writes also, but I would like to do that in a separate PR. Please let me know if I should include that change here only, Thanks!

fix: handling multiple failure/error scenarios during socket reads

---

README.md

Updating README for Multithreading

---

integration_tests/commands/http/echo_test.go
integration_tests/commands/http/exists_test.go
integration_tests/commands/http/expire_test.go

As mentioned on the issue, I've completed 2/5 of the given test cases (i.e. EXISTS and ECHO), and I'll also create PR for the remaining test cases soon
EXISTS test cases - screenshot
ECHO test cases - screenshot

Added Test Cases for EXISTS, ECHO and EXPIRE with HTTP Issue #737

---

docs/src/content/docs/commands/TTL.md

This PR resolves #810
- Refactored headings to match as per syntax requirement in issue #810
- Refactored formatting for `Parameters, Return values  , Examples` sections
- Refactored Errors
- Refactored Examples

docs: modified TTL #810

---

integration_tests/commands/http/object_test.go
integration_tests/commands/http/select_test.go
integration_tests/commands/http/set_data_cmd_test.go
integration_tests/commands/http/toggle_test.go
integration_tests/commands/http/touch_test.go
integration_tests/commands/http/ttl_pttl_test.go
integration_tests/commands/http/type_test.go

Tasks for #742 
Created test cases for above files in integration_tests/commands/async for HTTP server

#742 Added Http tests (9)

---

.github/ISSUE_TEMPLATE/report_command_bug.md

Fix #747: Updated test folder name in issue template

Fix test folder name in issue template

---

docs/src/content/docs/commands/INCR.md

This PR updates the documentation for the `INCR` command in DiceDB to improve clarity, consistency, and structure. Key changes include: ( this takes reference from the `SET` documentation )
1. **Return Values**:
- Replaced the general "Integer" return value with a detailed conditions table for successful and error scenarios.
2. **Error Handling**:
- Updated the error messages to use the consistent format `(error) ERROR ...` across all scenarios.
- Expanded error explanations to enhance understanding of common failure conditions (e.g., wrong type and overflow).
3. **Example Usage**:
- Enhanced example descriptions for better readability.
- Provided clearer context for error scenarios with non-integer values and overflow conditions.
4. **Additional Formatting**:
- Improved syntax and …

#837: audited and made the INCR docs consistent

---

docs/src/content/docs/commands/ECHO.md

This pull request adds documentation for the `ECHO` command in DiceDB. 
- Added details about the syntax and parameters of the `ECHO` command.
- Included examples of valid and invalid usage.
- Updated the documentation to clarify error messages and return values.
Fixes #872
To test the `ECHO` command, you can run the following command in the DiceDB terminal:

Add Documentation for ECHO command #872

---

integration_tests/commands/async/hkeys_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Add Support for HKEYS command. 

---

docs/src/content/docs/commands/TOUCH.md

documentation of the touch command made consistent.

docs: update TOUCH docs

---

docs/src/content/docs/commands/SADD.md

Updated: SADD Docs

---

docs/src/content/docs/commands/ECHO.md

fixes typos in ECHO.md (#919)

---

docs/src/content/docs/commands/JSON.NUMINCRBY.md

Fixes [JSON.NUMINCRBY audit and doc update](https://github.com/DiceDB/dice/issues/771).
- Updated formatting by referring [SET Command docs](https://dicedb.io/commands/set/)
- Use $ for path demonstration instead of .
- Added missing examples for JSON.NUMINCRBY usage

Audit  `JSON.NUMINCRBY` documentation for consistency

---

integration_tests/commands/http/expireat_test.go
integration_tests/commands/http/expiretime_test.go

As mentioned on the issue, I've completed the remaining test cases as well (i.e. for EXPIREAT and EXPIRETIME)
EXPIREAT test cases - screenshot
EXPIRETIME test cases - screenshot
Hii @apoorvyadav1111 @pratikpandey21 @JyotinderSingh ,
I'm requesting a review of these changes, please let me know if any iterations are required
Regards,

#737: Added Test Cases for EXPIREAT & EXPIRETIME with HTTP Issue

---

docs/src/content/docs/commands/LPUSH.md

Updates documentation for LPUSH command. Fixes #835

#835: docs: updated LPUSH documentation

---

docs/src/content/docs/commands/MSET.md

This pr closes #831 
**Changes**
- Refactored sections
- Parameters and return values converted into tabular form
- Cleaned up error messages
- Added additional info in behavior section

#831: Updated MSET Docs

---

docs/src/content/docs/commands/MGET.md

Updated the MGET Docs.
Fixes issue #823

Updated MGET Docs

---

docs/src/content/docs/commands/DEL.md

DOCS: Updated DEL Docs

---

docs/src/content/docs/commands/AUTH.md
internal/eval/eval.go

audited and updated docs for AUTH command

---

docs/src/content/docs/commands/JSON.GET.md

> [!IMPORTANT]  
> Please merge this PR after the below PR is merged 
> - https://github.com/DiceDB/dice/pull/968
1. Reformat parameters in a table
2. Update return values and reformat to table
3. Update examples headings
https://github.com/user-attachments/assets/af790131-12d5-4e91-8d64-c71733b690b4
Closes #776

Update the documentation for `JSON.GET` command (#776)

---

docs/src/content/docs/commands/KEYS.md

Resolves issue https://github.com/DiceDB/dice/issues/843
Audits and Changes:
Other issues found during auditing:
1. https://github.com/DiceDB/dice/issues/851

docs: audits and updates the KEYS command doc

---

docs/src/content/docs/commands/PERSIST.md

fixes #774 
I have updated the documentation of PERSIST command

docs: Update PERSIST command documentation (#774)

---

docs/src/content/docs/commands/BGREWRITEAOF.md

Fixes #787 
Updated documentation based on the code for BGREWRITEAOL

fix: Updated BRGREWRITEAOF.md

---

internal/eval/eval.go
internal/eval/eval_test.go

Changes that are done:
* Changed error messages for invalid JSONPath, invalid syntax etc.
* Changed the outputs where the result should only be an integer instead of list.
* This PR is for (#974) issue

#974: Updated JSON.ARRLEN to match RedisCLI outputs

---

integration_tests/commands/async/hmset_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

#651: FEAT: Added support for HMSET 

---

config/config.go
dice.toml
internal/worker/worker.go

This PR includes changes to get buffer size for `adhocReqChan` through config , default value is set as 20.

#999 Get adhocReqChan buffer from config

---

docs/src/content/docs/commands/EXPIRETIME.md

Fixes #797 
updated the docs for Expiretime command

Refactor EXPIRETIME command documentation (#797)

---

docs/src/content/docs/commands/EXPIRE.md

Fixes #811 
updated Expire docs

Updated EXPIRE command documentation

---

docs/package-lock.json
docs/src/content/docs/commands/HSCAN.md
docs/src/content/docs/commands/JSON.SET.md

Fixes: #795 
Hi team,
fixed the `json.set` documentation for dicedb.io. There are still inconsistencies in JSON.SET command between Redis and DiceDB but #381 is already created and assigned to someone. One of the additional tasks for #381 would be to update the documentation as per the changes.
I have not included all scenarios for error handling for now as we need to fix the inconsistencies before we add that in documentation.
Additionally, I have run `npm audit fix` for low vulnerabilities. If the change is not required, I can discard them.
Thanks
Apoorv

#795: Fix json.set doc + audit fix

---

CONTRIBUTING.md
docs/src/CLIENT.md
docs/src/content/docs/commands/EXPIREAT.md
docs/src/content/docs/commands/KEYS.md
docs/src/content/docs/commands/PTTL.md
integration_tests/commands/async/check_type_test.go
integration_tests/commands/async/dbsize_test.go
integration_tests/commands/async/flushdb_test.go
integration_tests/commands/async/json_test.go
integration_tests/commands/async/set_data_cmd_test.go
integration_tests/commands/http/check_type_test.go
integration_tests/commands/http/incr_test.go
integration_tests/commands/http/json_test.go
internal/clientio/resp.go
internal/eval/bloom.go
internal/eval/bloom_test.go
internal/eval/deque.go
internal/eval/eval.go
internal/eval/eval_test.go
internal/eval/execute.go
internal/store/eviction.go
internal/store/lfu_eviction_test.go
main.go

Common spelling fixes

---

docs/src/content/docs/commands/BFADD.md

Update BFADD command documentation

---

docs/src/content/docs/commands/SELECT.md

This Pull Request fixes #812 
**Changes**
- add `Syntax` section
- make `Parameters` section to table
- make `Return Value` section to table
- fix `127.0.0.1:6379` to `127.0.0.1:7379`

docs: audit and make documentation for command SELECT

---

config/config.go
dice.toml
integration_tests/commands/async/setup.go
integration_tests/commands/http/json_test.go
integration_tests/commands/http/setup.go
integration_tests/commands/resp/abort/server_abort_test.go
integration_tests/commands/resp/setup.go
integration_tests/commands/websocket/setup.go
integration_tests/config/config_test.go
integration_tests/server/server_abort_test.go
internal/eval/eval.go
internal/logger/logger.go
internal/observability/ping.go
internal/server/resp/server.go
internal/server/server.go
internal/shard/shard_thread.go
internal/sql/executerbechmark_test.go
internal/store/aof.go
internal/store/eviction.go
internal/store/evictionpool.go
internal/store/lfu_eviction_test.go
internal/store/store.go
internal/worker/worker.go
main.go

this pr includes logic grouping of config including http and websocket support with bug minor fixes

#991 Config enhancement with http and websocket properties

---

docs/src/content/docs/commands/DBSIZE.md

#841: docs: update `DBSIZE` docs

---

docs/src/content/docs/commands/RPUSH.md

#791: RPUSH docs fixed referencing SET command

---

docs/src/content/docs/commands/HGETALL.md

This pr closes #830 
**Changes**
- Refactored sections
- Refactored error messages
- Added additional error messages and examples
- Refactored CLI syntaxes

docs: Refactored HGETALL 

---

integration_tests/commands/http/hyperloglog_test.go
integration_tests/commands/resp/hyperloglog_test.go
integration_tests/commands/websocket/hyperloglog_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go
internal/eval/store_eval.go
internal/server/cmd_meta.go
internal/worker/cmd_meta.go

This PR closes #1032.
Here are things that are done

#1032: Migrates of PFADD, PFCOUNT, PFMERGE to Multi-threaded architecture.

---

docs/src/content/docs/commands/TTL.md

#1106 
Found this inconsistency when i was looking for commands which shows golang errors.

#1106 TTL Docs Inconsistency

---

docs/src/content/docs/commands/JSON.MGET.md

#803: Updating JSON.MGET command documentation

---

examples/leaderboard-go/go.mod
examples/leaderboard-go/go.sum
go.mod
go.sum
integration_tests/commands/async/qunwatch_test.go
integration_tests/commands/async/qwatch_test.go
integration_tests/commands/http/qwatch_test.go
integration_tests/commands/http/setup.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/execute.go
internal/server/httpServer.go
internal/server/utils/redisCmdAdapter_test.go
internal/server/websocketServer.go
internal/sql/constants.go

Renames QWATCH -> Q.WATCH for consistency

---

docs/src/content/docs/commands/GETEX.md

Audited GETEX documentation to be consistent to redis #821

#821 Audit and make documentation for command GETEX consistent

---

docs/src/content/docs/commands/EXISTS.md

#826 
CC @lucifercr07 
Let me know if i missed anything. Happy to contribute.

ENH: Audit EXISTS Docs

---

docs/src/components/Footer.astro
docs/src/content/docs/get-started/reactive-hello-world.mdx
docs/src/content/docs/get-started/realtime-leaderboard.mdx

- Added leaderboard tutorial
- Update paths for example/leaderboard

Adding leaderboard tutorial example

---

README.md

- improved formatting
- replaced playground-web with alloy
- reduced unwanted lines
- rewritten project story to better communicate our goals and community alignment
- added discord badge with invite link along with other badges

docs: improved README.md file

---

docs/src/content/docs/commands/ZREM.md
integration_tests/commands/http/zrem_test.go
integration_tests/commands/resp/zrem_test.go
integration_tests/commands/websocket/zrem_test.go
internal/eval/commands.go
internal/eval/eval_test.go
internal/eval/store_eval.go
internal/server/cmd_meta.go
internal/worker/cmd_meta.go

Adds support for [ZREM](https://redis.io/docs/latest/commands/zrem/)
PR Checklist
closes https://github.com/DiceDB/dice/issues/1125

#1125 Add support for ZREM

---

CONTRIBUTING/README.md
docs/CONTRIBUTING.md

Learnt through painful experience that it was important to fetch upstream before attempting to merge with upstream/master.

Minor CONTRIBUTING.md addition

---

integration_tests/commands/async/set_test.go
integration_tests/commands/http/set_test.go
integration_tests/commands/resp/set_test.go
integration_tests/commands/websocket/set_test.go
internal/eval/eval_test.go
internal/eval/store_eval.go

The above was not same in the Current Dice db implementation , i have fixed it, kindly verify once and let me know if there is something that is need to be change and updated too.
It makes it consistent with current DOCs and Redis Implementation.  
#786
cc @apoorvyadav1111

FIX: SET Command Inconsistency

---

internal/eval/eval.go

Hi team,
This PR is created to address few comments left on #1117 and to address those on priority

#1117: Addressed review comments

---

internal/worker/cmd_compose.go

Hello!
This commit just cleans up a couple tiny issues with the in-code documentation I discovered while messing around with the code. Hope such contributions are not discouraged :)
Thanks

fix minor documentation issue

---

integration_tests/commands/http/zset_test.go
integration_tests/commands/resp/zset_test.go
integration_tests/commands/websocket/zset_test.go

Changes:
* Updated Integration tests of ZPOPMIN command to check outputs with ZCOUNT command

Updated ZPOPMIN command tests to check outputs with ZCOUNT command

---

docs/src/content/docs/commands/TYPE.md
integration_tests/commands/http/type_test.go
internal/eval/eval.go

1. Added zset Type too to cover for ZADD and GEOADD.
2. Added Tests for them too.
3. Added Docs and Cover everything for TYPE Command and making it consistent with other DOCs.
#1280
cc @apoorvyadav1111 @JyotinderSingh

#1280 Feat: Type Docs 

---

docs/package-lock.json
docs/package.json
docs/public/logo.png:Zone.Identifier
docs/src/pages/index.astro

Fixes #1299 
| Before | After |
| - | - |
| ![image](https://github.com/user-attachments/assets/90c40e6b-149d-4428-8b72-7fffc224b302) | ![image](https://github.com/user-attachments/assets/117bab50-be0b-4bbb-80c4-564cdd268732) |

Consistent blog card on website

---

integration_tests/commands/http/bit_test.go
integration_tests/commands/resp/bit_test.go
integration_tests/commands/websocket/bit_test.go
internal/eval/store_eval.go

#1114: changes for issue 

---

docs/src/content/docs/commands/BITFIELD_RO.md
docs/src/content/docs/commands/COMMAND HELP.md
docs/src/content/docs/commands/DECR.md
docs/src/content/docs/commands/EXPIRE.md
docs/src/content/docs/commands/EXPIREAT.md
docs/src/content/docs/commands/EXPIRETIME.md
docs/src/content/docs/commands/HEXISTS.md
docs/src/content/docs/commands/HINCRBY.md
docs/src/content/docs/commands/HINCRBYFLOAT.md
docs/src/content/docs/commands/HKEYS.md
docs/src/content/docs/commands/HRANDFIELD.md
docs/src/content/docs/commands/HVALS.md
docs/src/content/docs/commands/INCR.md
docs/src/content/docs/commands/LINSERT.md
docs/src/content/docs/commands/LLEN.md
docs/src/content/docs/commands/LPOP.md
docs/src/content/docs/commands/LPUSH.md
docs/src/content/docs/commands/LRANGE.md
docs/src/content/docs/commands/PTTL.md
docs/src/content/docs/commands/RPOP.md
docs/src/content/docs/commands/RPUSH.md
docs/src/content/docs/commands/SMEMBERS.md
docs/src/content/docs/commands/TTL.md
docs/src/content/docs/commands/ZRANK.md

- Closes #1324 
- This PR adds hyperlink for commands in the documentation for easily navigation.

Add hyperlink for commands

---

docs/src/content/docs/commands/SETEX.md

Add documentation for SETEX command

add: documentation for setex command

---

docs/src/content/docs/commands/GEOHASH.md
integration_tests/commands/http/geo_test.go
integration_tests/commands/resp/geo_test.go
integration_tests/commands/websocket/geo_test.go
internal/eval/commands.go
internal/eval/eval_test.go
internal/eval/geo/geo.go
internal/eval/store_eval.go
internal/iothread/cmd_meta.go

Closes #1248 
implement GEOHASH command and related tests.

#1248: Add support for command GEOHASH

---

config/validator.go

Make processedFields a set

---

internal/eval/countminsketch.go

Single matrix memory allocation in DeserializeCMS

---

config/config.go
dicedb.conf
integration_tests/commands/http/setup.go
integration_tests/commands/resp/setup.go
integration_tests/commands/websocket/setup.go
internal/cli/cli.go
internal/commandhandler/cmd_meta.go
internal/commandhandler/commandhandler.go
internal/server/resp/server.go
internal/shard/shard_thread.go
internal/store/aof.go
internal/wal/wal.go
internal/wal/wal_aof.go
internal/wal/wal_null.go
main.go

Adding minor refactoring to the WAL and implementing basic interface for WAL Replay by adding a separate new commandHandler for walReplay.
cc @arpitbbhayani @JyotinderSingh @soumya-codes @AshwinKul28 @psrvere @gauravsarma1992

Adding WAL Replay functionality

---

internal/cmd/cmd_echo.go
internal/cmd/cmd_ping.go

- Added echo command for ironhawk engine
- Minor refactor to use predefined error message
Closes: [#1429](https://github.com/DiceDB/dice/issues/1429)
Todos:
- Add fixes for memory reference issue related to: [#1431](https://github.com/DiceDB/dice/pull/1431)

Add echo command for new ironhawk engine

---

internal/cmd/cmd_decr.go
internal/cmd/cmds.go

Migrate DECR command to support ironhawk engine
fixes #1426

feat: port `DECR` command

---

internal/cmd/cmd_expireat.go
internal/cmd/cmds.go

Implement EXPIREAT command

---

internal/cmd/cmd_getx.go

port GETEX command to iron hawk
fixes: https://github.com/DiceDB/dice/issues/1456

port GETEX command to IronHawk

---

internal/cmd/cmd_type.go
internal/object/object.go

This PR migrates `type` command to ironhawk engine.

Port  TYPE command

---

internal/cmd/cmd_incrby.go
tests/commands/ironhawk/get_test.go
tests/commands/ironhawk/incr_test.go
tests/commands/ironhawk/incrby_test.go

Updated test cases for INCR and INCRBY
fixes https://github.com/DiceDB/dice/issues/1493 & https://github.com/DiceDB/dice/issues/1494

Integration tests fixes - INCRBY & INCR

---

tests/commands/ironhawk/ttl_test.go

Added test cases for ttl

---

internal/cmd/cmds.go
internal/server/ironhawk/iothread.go

**_meta** is never nil, so the **if** condition will never trigger. 
If we send an unknown command, the DiceDb server crashes

Fix for Command Meta

---

docs/src/styles/main.scss

fix button text color on focus

---

internal/cmd/cmd_hget_watch.go
tests/commands/ironhawk/hget_watch_test.go

Adding support for `HGET.WATCH` cmd

---

add_license_notice.sh

✅ **Handles package declaration properly**  
✅ **Preserves file permissions**  
✅ **Avoids unnecessary grep calls in the loop**  
✅ **Uses mapfile for efficiency (reduces subshells)**  
✅ **More optimized find command usage**

Optimize license header script and improve efficiency

---

internal/cmd/cmd_zpopmin.go
internal/eval/sortedset/sorted_set.go

ZPOPMIN Migration

---

internal/cmd/cmd_zcard.go

Ported ZCARD command 

---

internal/cmd/cmd_get.go
internal/cmd/cmd_getdel.go
internal/cmd/cmd_getex.go
internal/cmd/cmd_getset.go
tests/commands/ironhawk/get_test.go

Server doesn't crash if Obj Type is not present and float support in GET Command
fixes #1697 #1698

Server doesn't crash if Obj Type is not present and float support in GET Command

---

internal/server/ironhawk/iothread.go

Fixes #1745
This PR handles issue #1745 by ensuring IO threads shut down cleanly using context cancellation, preventing server hangup during a SIGINT. The issue is with  serverWire.Receive() call  which is blocking in nature, called via wg.Wait() in ironhawk/main.go
.

Graceful shutdown fix
