DiceDB/dice

main.go

For issue #18 - Adds unicode for dice, as a replacement for emoji

Add dice unicode "⚄" instead of dice emoji

---

core/resp.go
server/async_tcp.go
server/sync_tcp.go

The issue behind **Cross Protocol Scripting** is that RESP is a serialization protocol and hence any abuse of it by providing incompatible protocols increases the attack surface, Its security risk in the context of RESP spec implementation safety, a few jargon characters could break your RESP handler.  This PR disables "Cross Protocol Scripting", refer to the issue https://github.com/DiceDB/dice/issues/12.

Disable Cross Protocol Scripting

---

core/eval.go

the `exDurationSec` var was wrongly configured. The set command may have multiple flags in future and **ex** can be in any position.
Issue Link:
https://github.com/DiceDB/dice/issues/33

bug: resolved bug for exDurationSec

---

server/async_tcp.go

Because of typo, we were accidentally setting the server file descriptor to non blocking again and again

For all client connections, set the file descriptor to be non-blocking so that any blocking operation errors out

---

.github/workflows/release.yml
.goreleaser.yaml

- Issue#27, Added GitHub actions to build Dice for
OS : linux and darwin
arch: amd64
- Used Goreleaser-actions for github which gets triggered on pushing with new tag.
- Need to follow Semantic versioning
[Follow-up] : 
Goreleaser also provides following features but I have not added them in this issue.
1. Currently the release files are tar files, for future this could be changed to release .rpm, .deb, .apk, docker image ,etc.
2. Can create a webhook for discord to make announcements in discord channels in new releases.

Added GitHub actions to build Dice for platforms

---

core/xencoding/byte_utils.go
core/xencoding/int.go
tests/xencoding_int_test.go

Addresses issue: #81
I chose to re-implement `varint` and not use existing implementation because I forsee us needing to change `varint` implementation for advanced data structures we would be supporting.
I have also added tests for the same. I am calling our encoding scheme `XEncoding` - an umbrella that holds space and cache-efficient encoding for int, string, list, and much more.

`varint` implementation for unsigned int

---

.devcontainer/devcontainer.json

With this now users can directly setup dev infra environment in vs-code .
This will ope the vs code with the all depenedencies and UI with the vscode to make it more seamless

Setting up optional infra for devccontainer in vscode

---

storm/set/main.go

Fix Unreachable Code in stormSet Function
Description:
This pull request addresses the "unreachable code" error encountered in the stormSet function. The issue arises due to the conn.Close() statement being unreachable after a return statement. To resolve this, the code has been rearranged to ensure that the conn.Close() statement is reachable and executed properly. Additionally, a defer statement has been added at the beginning of the function to ensure proper cleanup of resources even if the function returns early due to an error. This improves the reliability and maintainability of the codebase.
Changes Made:
1. Moved the conn.Close() statement to a reachable location in the function.
2. Added a defer statement to ensure the connection is closed when the function exits, improving code …

Fix unreachable code in storm set function

---

server/async_tcp.go

Error message with status code.
No error when there is only one instance

[Fixes] #95 Added exit status and log message when user tries to spin a new instance on same port.

---

core/bloom_test.go

Removed parallel execution from TestUpdateIndexes and TestGetOrCreateBloomFilter, were causing a race condition and  interfering with the BF state causing test failure

#132 : Removed parallel execution from TestUpdateIndexes and TestGetOrCreateBloomFilter

---

core/queueint.go
core/queueint_test.go

To optimise the `QueueInt` implementation. Corresponding issue #68 
- Added an interface `core.QueueIntI` for `core.QueueInt` to try out different implementations
- Added a doubly linked list implementation `QueueIntLL` and a basic implementation wrapping an `int64` slice `QueueIntBasic`
- Added benchmark tests to run Inserts for the different implementation. All other operations depend on Inserts`therefore this serves as a good benchmark to begin with
`QueueIntBasic` performs best with space and time. Raises the question - Why do we need a custom serialisation to bytes to store and remove?
Sample output of the benchmark tests on an M1 Mac with 16GB Ram is as follows
```
goos: darwin
goarch: arm64
pkg: github.com/dicedb/dice/core
BenchmarkInsert20-8          	 2086051	       556.9 ns/op …
```

Added benchmarks for queueint - #68

---

.github/workflows/linter.yml
.github/workflows/tests.yml

Adding linter check for Pull requests to save some trivial review time.
Atm limited to new changes only, but can be extended to all code in future as we cleanup old lint errors.

introducing linter for new code changes only

---

core/eval.go
tests/command_list_test.go
tests/commands_test.go

Added list command. Please review and provide your inputs.
Summary of change:
- Added Constants for Command names to keep it easy to add new commands, as well as reuse commands in tests
- Added List command
- Added test and benchmark
Benchmark results - (first time running benchmark so i don't have a baseline to compare if this code was good or shit). I could use some help here.

#149 : Add list command for dicedb

---

core/eval.go
core/resp.go
tests/hello_test.go

Adds support for `HELLO` command to negotiate protocol version and provide other server information.
Also fixes a bug in RESP encoding logic for `[]interface{}`
Added related integration test.

Add support for HELLO command.

---

.github/workflows/linter.yml

We should enable linting for entire codebase now that we have addresed all existing lint errors.

Enable linting for entire codebase

---

core/eval.go
core/store.go
server/async_tcp.go

Refactor WatchList implementation using sync.Map for thread safety and performance improvements
- Replaced `WatchList` and `WatchListMutex` with `sync.Map` for concurrent access.
- Added `AddWatcher` and `RemoveWatcher` functions to manage watchers.
- Updated `evalQWATCH` to use the new `AddWatcher` function.
- Modified `WatchKeys` to utilize `sync.Map` methods for iterating and managing clients.
- Simplified regex matching and client notification logic within `WatchKeys`.

Use sync.Map for watching queries

---

.github/workflows/tests.yml

Issue - https://github.com/DiceDB/dice/issues/164
The PR disables running integration tests when running GitHub workflow.
The PR also changes the build and unit test steps to use the Makefile commands to reuse the same commands as defined in the Makefile.
The PR has been tested both locally and via github workflows in the downstream repository.

Disable running integration tests in github workflows

---

server/async_tcp.go

Removes a query from the query watch-list if no clients are watching it. This can help prevent memory leaks due to stale queries.

Remove query from watchlist if no clients are watching it.

---

core/aof.go
core/eviction.go
core/executor.go
core/expire.go
core/queueref.go
core/stackref.go
core/store.go

With the addition of the WatchKeys goroutine (to enable real-time reactive query subscriptions), concurrent reads can happen on the `store` and `keypool` maps.
This change adds RW locks to guard access to these data structures to prevent race conditions.
These benchmarks test existing workflows which are mostly single-threaded, we may see some unavoidable slowdowns once we benchmark more sophisticated scenarios (involving multiple clients, some of which are subscribing to existing queries.
Overall, the performance is quite close to the thread-unsafe implementation, and the time taken seems to have increased within reason.
| Benchmark                  | Iterations | Time (ns/op) | Memory (B/op) | Allocations (allocs/op) |
|----------------------------|------------|--------------|----------- …

Ensure thread-safe access to store and keypool

---

server/async_tcp.go
tests/qwatch_test.go

Improved QWATCH Tests to ensure reactive functionality works reliably with multiple subscribers.
* Replaced `ctx.Done()` with `cancel()` in `RunAsyncTCPServer` for idiomatic abort signal handling.
* Refactored TestQWATCH and TestQWATCHWithSDK to support multiple subscribers.

Improve QWATCH tests to validate functionality with multiple subscribers.

---

docs/setting-up-in-aws.md
pulumi/Pulumi.dev.yaml
pulumi/Pulumi.yaml
pulumi/__main__.py
pulumi/requirements.txt

Add Pulumi script to automate the deployment of DiceDB on AWS. 
1. Configure AWS credentials:
```
aws configure
```
2. Create and activate a virtual environment:
```
python -m venv venv
source venv/bin/activate  # On Windows, use `venv\Scripts\activate`
```
3. Install requirements:
```
pip install -r requirements.txt
```
4. Create a new Pulumi stack or use an existing one:
```
pulumi stack init my-stack  # Create new stack
pulumi stack select dev     # Use existing dev stack
```
5. Review and update inputs in the Pulumi config file (`Pulumi.<stack-name>.yaml`)
6. Preview the changes:
```
pulumi preview
```
7. Deploy the infrastructure:
```
pulumi up
```
- Uses Pulumi with Python for infrastructure as code
- Creates a new VPC, subnet, internet gateway, and route table
- Provisions an EC2 …

pulumi script to spinup and setup any AWS VM #139

---

core/commands.go
core/eval.go

#182 
Dice cmds via struct
Summary of change:
Designed a struct to implement dice commands
Implementation details:
`DiceCmdMeta` encapsulates information about a dice command. A map `map[string]DiceCmdMeta{}` stores all the `DiceCmdMeta` _objects_ and acts as a source of truth for all the commands.
- `Eval` method contains business logic of the command.
- if a command is not a valid DiceDB command then an error message is returned, earlier an invalid cmd was resolved as `PING`.  This change is taken from Redis (refer img below)
- few commands which requires `Client` struct are handled separately in `func executeCommand` as it was earlier. Handling them gracefully is a topic of discussion.
- `Info` and `Docs` are kept placeholder and will be accomplished in  #148 and #146 respectively. …

#182: Refactor command handling for maintainability

---

core/commands.go
core/eval.go
tests/command_count_test.go

Added support for  count command. Please review.
COMMAND COUNT is used to get total number of commands in dicedb.
redis documentation : https://redis.io/docs/latest/commands/command-count
This is my first PR and just getting started with the project. I have referred @yashs360's PR #150 for making the code changes. Thank you @yashs360 
- Reused used the changes made by @yashs360  in PR #150 for adding constants for command names. Thanks @yashs360.
- Updated the eval methods as per PR #158  to support COMMAND|subcommand, thanks @kakdeykaushik
-  Added method to get the total number of commands.
- Added test and benchmark.
Benchmark results
Issue : #145

#145 : Added support for COMMAND COUNT command 

---

core/dsql.go
core/dsql_test.go
core/executor.go
core/executor_test.go

This PR adds support for WHERE clause in DSQL.
1. Updated `DSQLQuery` struct to include a `Where` field of type `sqlparser.Expr`.
2. Updated `ParseQuery` to support WHERE clauses.
4. Updated `ExecuteQuery` to evaluate WHERE clause for each row.
5. Added support for complex WHERE conditions using a recursive analyzer.
6. Implemented type-safe comparisons for string, int, and float values.
7. Added extensive test cases for both parser and executor to cover various scenarios and edge cases.
- Support for basic comparison operators (=, !=, <, <=, >, >=) in WHERE clauses.
- Support for AND/OR logical operators.
Added comprehensive test cases for parser and executor.
- Logic needs to be extended to support JSON values once Dice supports them.

Add WHERE Clause Support to DSQL Parser and Executor

---

core/commands.go
core/eval.go
core/object.go
go.mod
go.sum
tests/json_test.go

#165 Added support for JSON.SET and JSON.GET operations; (jsonpath operations is wip)
@JyotinderSingh the existing `Encode` function seems to be sophisticated enough for handling the encoding of the json strings to RESP2. 
However, in RESP3 standard; things have been changed a bit in case of handling of [maps](https://redis.io/docs/latest/develop/reference/protocol-spec/#maps) 
Kindly take a look at the following docs/discussion:
https://redis.io/docs/latest/develop/data-types/json/resp3/
https://github.com/RedisJSON/RedisJSON/issues/1090
https://redis.io/docs/latest/commands/json.set/

Add support for JSON 

---

core/dencoding/int.go
core/dencoding/int_test.go

- Added support for signed integer encoding, this would allow us to support signed integer stacks and queues.
- Added unit tests to validate correctness.
```
=== RUN   TestDencodingInt
--- PASS: TestDencodingInt (0.00s)
PASS
ok      github.com/dicedb/dice/core/dencoding   0.215s
```
- Added the benchmarks
```
=== RUN   BenchmarkEncodeDecodeInt
BenchmarkEncodeDecodeInt
BenchmarkEncodeDecodeInt-12     69471247                16.97 ns/op            3 B/op          1 allocs/op
PASS
ok      github.com/dicedb/dice/core/dencoding   1.627s
```

#183: Support for signed integer dencoding

---

core/commands.go
core/eval.go
tests/command_getkeys_test.go

Returns [Array reply](https://redis.io/docs/latest/develop/reference/protocol-spec/#arrays) of keys from a full Redis command.
- Added arity to command meta data. This is similar to how redis checks for command length. A positive rarity will give exact argument length and negative rarity mean minimum argument length. E.g. [get](https://github.com/redis/redis/blob/unstable/src/commands/get.json) and [del](https://github.com/redis/redis/blob/unstable/src/commands/del.json)
- Added key specs to identify the keys
- The metadata required for `COMMAND GETKEYS` should ideally not be coded just in the function so that we will not forget to add them when we add a new command
- Ideally, we can check arity checks before evaluating the command but I think that should be done in another PR. 
- There …

#147: Add support for COMMAND GETKEYS command

---

core/eval.go
tests/set_test.go
tests/setup.go

This pull request adds support for the XX option to the SET command, similar to the XX option in Redis. The XX option sets the value of the key only if it is already present.
Solving the issue https://github.com/DiceDB/dice/issues/205
1. **Implemented XX Option:**
- Updated the SET command to handle the XX option.
2. **Unit Tests:**
- Added unit tests for the XX option.

#205: Add support for XX in SET command

---

core/resp.go
tests/set_test.go

Fixes: Issue #213 
- Added a corner case for handling `RESP_NIL`
- Added a test case in `tests/set_test.go` where the expected output for a command in `RESP_NIL`

fixed readBulkString to handle RESP_NIL

---

core/store.go
tests/get_test.go

In file store.go, func Del(k) requires both locks to delete the key, however,  in Get(k), we were releasing only one. This fix implements releasing both locks before calling Del(k) and acquiring both locks again.
Tested manually on local:

#201: Fix for expired key crash

---

core/io.go
core/io_test.go

- code for handling case where no data is read and no error is returned in DecodeOne function in io.go file
- Test case for the above mentioned case in io_test.go
* Evidence of sufficient testing. You ``MUST`` indicate the tests done, either manually or automated.
- I ran the submitted unit test along with all the tests. They all passed
- I checked the functionality by using "exit" and ^d command to check if I was allowed to connect to the server again. It ran successfully.

#196: Fixed DiceDB server reconnection error.

---

core/dencoding/int_test.go

- Added test case for MinInt64
```
=== RUN   TestEncodeDecodeInt64Min
--- PASS: TestEncodeDecodeInt64Min (0.00s)
PASS
ok      github.com/dicedb/dice/core/dencoding   (cached)
```

#221: Test Case for MinInt64

---

core/dencoding/dencoding_benchmark_test.go
core/dencoding/int_test.go

- Added benchmark for negative numbers and number close to MinInt64, MaxInt64
```
=== RUN   BenchmarkMinMaxEncodeDecodeInt
BenchmarkMinMaxEncodeDecodeInt
BenchmarkMinMaxEncodeDecodeInt-12       49743938                23.24 ns/op            7 B/op          1 allocs/op
PASS
ok      github.com/dicedb/dice/core/dencoding   1.396s
```

#222: Added Benchmark for negative number and close to MinInt64, MaxInt64

---

core/eval.go
core/eval_test.go
core/store.go
tests/set_test.go

- Added support for `PXAT` in `SET` command similar to the [PXAT option in Redis](https://redis.io/docs/latest/commands/set/).
- Format: ` SET key val PXAT unix-time-milliseconds`
- Added unit and integration test for the same.
- Currently there's no mechanism to handle immediate expiration for past PXAT timestamps. Hence added `setExpiry` to be set to `0 ms` when creating `NewObj`.
- Invalid values for `PXAT` e.g: `str`, `-ve int` etc.
- Expiry of keys associated with valid UNIX ms
- Expiry of keys associated with invalid UNIX ms

feat: [GH-203] Add support for PXAT in SET command

---

core/commands.go
core/eval.go
core/store.go
tests/keys_test.go

This PR aims to support `KEYS` command like [redis KEYS](https://redis.io/docs/latest/commands/keys/)

feat: support KEYS command

---

core/eval.go
go.mod
go.sum
tests/json_test.go
testutils/json.go

@JyotinderSingh I have used https://github.com/ohler55/ojg for jsonpath support, after having tried multiple different ones.
Support for pretty much all [redis JSONPATH](https://redis.io/docs/latest/develop/data-types/json/path) operations is available, except for the following:
```
> JSON.GET bikes:inventory '$..[?(@.specs.material =~ "(?i)al")].model'
> JSON.SET bikes:inventory $.inventory.mountain_bikes[0].regex_pat '"(?i)al"'
> JSON.SET bikes:inventory $.inventory.mountain_bikes[1].regex_pat '"(?i)al"'
> JSON.SET bikes:inventory $.inventory.mountain_bikes[2].regex_pat '"(?i)al"'
> JSON.GET bikes:inventory '$.inventory.mountain_bikes[?(@.specs.material =~ @.regex_pat)].model' 
```
You can find a comprehensive testing script [here](https://gist.github.com/Maveric-k07/e59b3d8f8f43e889c976 …

#161: Adds JSONPath Support

---

config/main.go
core/comm.go
core/commands.go
core/eval.go
core/session.go
core/session_test.go
go.mod
go.sum
main.go
server/async_tcp.go

https://github.com/DiceDB/dice/issues/141
Prior to Redis 6, authentication for a connection was enabled by passing in `requirepass` in the redis.conf or while starting the redis server. If the above config is set, prior to any command, the authentication has to be by running the following command:
```
AUTH '<password>'
```
[
](url)
`requirepass` can be set in the config by changing `config/main.go` before running the server.
The storage of user credentials and ACLs will be implemented in the subsequent PRs.

Add support for Basic Auth

---

core/eval.go
tests/set_test.go

Hi @JyotinderSingh, I tried fixing the test case by adding type in the file but the test failed due to no support for EXAT option in set. I checked the PR for this addition and found out that subsequent PRs have removed the EXAT option. Hence, the EXAT support must be added again.
For now, I removed the test case testing EXAT functionality. 
Please review.

FIX: Removed old cases -> Added EXAT + new tests

---

tests/incr_test.go
tests/set_test.go

Hi @JyotinderSingh, this PR fixes the following:
1. incr_test.go:  ran tests without deleting keys leading to failed test cases when all tests are run.
2. set_test.go: Delay is reduced for quicker testing.
No test cases are added. Existing unit tests and integration tests are success.
Please review

Fixes in incr test and set test

---

core/eval.go
tests/json_test.go

**Description** : JSON.SET NX|XX invalid options handling added. In the future if we need to add more options after NX|XX then this logic needs to be updated, for now we are assuming that NX|XX is last option in JSON.SET command.
**Reference Pr** : https://github.com/DiceDB/dice/pull/228
**Testing** : Added tests for various invalid combinations of nx and xx json.set commands.

JSON.SET NX|XX invalid options handling

---

core/executerbechmark_test.go
core/store.go

This PR solves the issue of constant high memory usage when running `go test -bench=. -test.benchmem executerbechmark_test.go`. 
The memory allocated to a map grows as and when you start storing data in it. When you delete data from a map, Go doesn't automatically free up the memory and keeps it allocated to the map. So when the next set of Benchmarking tests ran, it reused some of the deleted memory and the memory footprint remained the same as the last benchmark test with the high number of keys.
In order to actually free the occupied memory and allocate a new block of memory, this PR initialises the data stores in the store.go before running every benchmark test. Looks like the memory footprint reduces again before every benchmark test. …

Reset datastores before every benchmark test

---

core/store.go

PR to address: [issue](https://github.com/DiceDB/dice/issues/267)
Add `WatchEvent` to `DelByPointer` function

#267: Emit `WatchEvent` from `DelByPointer` function

---

core/eval.go
tests/json_test.go

Fixes #272 
- uses strings.HasPrefix to verify invalid json error
- uses sonic.UnmarshalString; giving better performance
Average time test1000 iteration on simple, nested and complex json objects as in [json_test.go](https://github.com/DiceDB/dice/blob/master/tests/json_test.go)
```
1st trial
Simple JSON - Avg Unmarshal: 4.742µs, Avg UnmarshalString: 2.676µs
Nested JSON - Avg Unmarshal: 6.311µs, Avg UnmarshalString: 4.724µs
Complex JSON - Avg Unmarshal: 24.45µs, Avg UnmarshalString: 22.57µs
2nd trial
Simple JSON - Avg Unmarshal: 2.961µs, Avg UnmarshalString: 3.19µs
Nested JSON - Avg Unmarshal: 7.009µs, Avg UnmarshalString: 4.521µs
Complex JSON - Avg Unmarshal: 24.977µs, Avg UnmarshalString: 24.551µs
```
@JyotinderSingh

fixes failing TestJSONSetWithInvalidJSON 

---

core/store.go

https://github.com/DiceDB/dice/issues/298 
The GET call may perform deletion or touch, which should be done under write locks.

#298: Acquire write lock for GET call

---

tests/discard_test.go

This PR aims to improve test coverage. Added testcases for `DISCARD` command
Issue: https://github.com/DiceDB/dice/issues/79

#79: Added test case for DISCARD command

---

core/queueref.go
core/queueref_test.go

Unit test cases for `QueueRef.Remove()` and benchmarking for `QueueRef`.
- Test for removing from queue with single non-expired keys.
- Test for removing from queue with multiple non-expired keys.
- Test for removing from queue with expired keys before non-expired.
- Test for removing from queue with multiple expired keys before non-expired.
- Test for removing from queue with all expired keys.
- Benchmark `Queueref` by inserting expired, non-expired and expired keys in order and removing them.
[benchmark_results.txt](https://github.com/user-attachments/files/16571824/benchmark_results.txt)
Issue : #184 
Thank you @JyotinderSingh

#184 : Test cases and benchmarking for queueref remove

---

core/eval_test.go

- Adding unit tests for `eval.go` file
- Few test cases are blocked due to [GH-201](https://github.com/DiceDB/dice/issues/201), would update once issue is resolved.

#198: Adding unit tests for eval.go file

---

core/commands.go
core/eval.go
tests/getex_test.go

Addresses  #275 
- Support for GETEX Key command along with expiry options
* Design document, if any.
* Information on any implementation choices that were made.
* Evidence of sufficient testing. You ``MUST`` indicate the tests done, either manually or automated.
Added tests in tests/getex_test.go file

Feature added: getex command with args support for #275

---

core/bloom.go
core/bloom_test.go
core/bytearray.go
core/bytearray_test.go
core/bytelist.go
core/bytelist_test.go
core/commands.go
core/deep_copy.go
core/eval.go
core/queueint.go
core/queueref.go
core/stackint.go
core/stackref.go
tests/copy_test.go

This PR adds support for COPY command. Redis creates a deep copy of objects before adding it to the db. I have done the same thing and have added DeepCopy functions to the different data structures in the codebase. I have also added tests for the deep copy functions.

Closes #277 Support for COPY command

---

core/commands.go
core/eval.go
tests/object_test.go
tests/touch_test.go

Added support for the `TOUCH` command as per Redis and `OBJECT IDLETIME key` as per Redis.
Added tests for both commands in tests folder.
* Design document, if any.
* Information on any implementation choices that were made.
The reason to implement  `OBJECT IDLETIME key`, standalone from other subcommands is due to no support for ref and freq for keys and object for now. However, I assumed that having `object idletime` is essential to verify the effect of `TOUCH` command. In addition to this, I have carefully structured `OBJECT` for extension for subcommands in the future.
* Evidence of sufficient testing. You MUST indicate the tests done, either manually or automated.
Added new tests

Feature added support for TOUCH and OBJECT IDLETIME

---

core/commands.go

a tiny fix
in command.go there is :
`
jsonsetCmdMeta = DiceCmdMeta{
Name: "JSON.SET",
Info: `JSON.SET key path json-string
Sets a JSON value at the specified key.
Returns OK if successful.
Returns encoded error message if the number of arguments is incorrect or the JSON string is invalid.`,
Eval:     evalJSONSET,
Arity:    3,
KeySpecs: KeySpecs{BeginIndex: 1},
`
but we could add NX or XX so the Arity should be -3
such as below:
`
JSON.SET user $ '{"name":"123","age":18,"language":["java","python","go"]}'
JSON.SET user $.amount '1.26' XX
`

fix:correct the JSON.SET command Arity

---

core/eval.go
core/eviction.go
core/expire.go
core/queueref_test.go
core/session.go
core/session_test.go
core/store.go
server/async_tcp.go
server/utils/time.go

The PR introduces an abstraction around the `time.Now()` method to allow different treatment of the variable based on the environment `GetCurrentTime()` is used in.
Using the `MockClock`, tests would be able to progress the time manually without having to actually having to sleep for the duration.
This would speed up the tests which are currently relying on the time.Sleep functionality.

Added stubbed time for tests

---

core/executerbechmark_test.go
core/executor.go
core/executor_test.go
tests/qwatch_test.go

- Added JSON Support to where clause
- We can now query nested JSON fields
- Added unit and integration tests
- Performed Benchmarking, Here are the becnhmark results [JsonQueryBenchmark.txt](https://github.com/user-attachments/files/16645736/JsonQueryBenchmark.txt)

#189: Add JSON Support to where clause

---

core/dsql.go
core/executor.go
core/executor_test.go
internal/constants/constants.go
tests/qwatch_test.go

1. Improved type inference and conversion for JSON values, supporting boolean and null types.
2. Optimized the `isInteger` function to avoid expensive string conversions.
3. Added support for boolean and nil types in JSON fields.
4. Updated constant definitions to include boolean and null types.
5. To reduce flakiness, improve test assertions in both DSQL and QWATCH tests to compare actual JSON structures instead of string representations.

Improves JSON WHERE clause evaluation performance

---

core/eval.go
core/session.go

The error messages for AUTH command were inconsistent to what Redis outputs. Made them consistent now.

AUTH error message made consistent with Redis

---

core/commands.go
core/eval.go
core/eval_test.go

PR to address: Support for command `EXPIRETIME`
Link to [issue](https://github.com/DiceDB/dice/issues/284)
* EXPIRETIME returns the absolute Unix timestamp (since January 1, 1970) in seconds at which the given key will expire
* args should contain only 1 value, the key
* Returns expiration Unix timestamp in seconds.
* Returns -1 if the key exists but has no associated expiration time.
* Returns -2 if the key does not exist.

#284: Add support for command `EXPIRETIME`

---

core/bytelist.go
core/commands.go
core/dencoding/int.go
core/deque.go
core/deque_test.go
core/eval.go
core/object.go
core/queueint_test.go
tests/deque_test.go

In this PR, I add a new backing data structure `DequeI`, and like `QueueI` there's two implementation of it:
- `QueueBasic`: use a byte slice to store the data, but it involves reallocating and copying huge block of data when growing the slice.
- `Queue`: use the `byteList` structure to store the data, giving the minimum size of every node of `byteList` to minimize down the number of memory fragments, and the size of block of memory need to allocate or copy every time is also under preciser control.
About the encoding of every element inside `Deque`, after investigation to the redis implementation of the `listpack` data structure, I make a "copy" of it in golang, element is encoded orderly as [enc, data, backlen], where backlen is for supporting decoding from the tail (or say the rightest …

#244 feat: deque for [l/r][push/pop]

---

core/commands.go
core/eval.go
core/eval_test.go
core/resp.go
core/store.go

support for command `DBSIZE`
Link to [issue](https://github.com/DiceDB/dice/issues/278)
* Return the number of keys in the database.

#278: Add support for command `DBSIZE`

---

core/commands.go
core/eval.go
core/eval_test.go
internal/constants/constants.go
server/utils/jsontype.go
server/utils/jsontype_test.go

Link to #342 
-  [JSON.TYPE] command return the value type that [JSON.GET] command returns.
the json value type is similar to the redis command [JSON.TYPE] return.
- added unit-test and integration tests

#342: feat: add support for json.type command

---

core/commands.go
core/eval.go
core/eval_test.go
core/store.go
tests/expireat_test.go

PR to address: Support for command EXPIREAT
Link to https://github.com/DiceDB/dice/issues/283
EXPIREAT sets a expiry time(in unix-time-seconds) on the specified key in args
args should contain 2 values, key and the expiry time to be set for the key
The expiry time should be in integer format; if not, it returns encoded error response
Returns RespOne if expiry was set on the key successfully.
Once the time is lapsed, the key will be deleted automatically

#283: Add support for command EXPIREAT

---

core/eval.go
core/eval_test.go
tests/set_test.go

Fixes the type casting logic for SET and GET operations. Presently all values are stored and retrieved as strings. This PR fixes this behavior by introducing type type-casting logic into the eval flow.
The same needs to be done for other methods which set and get values.
Added new test cases and modified few existing ones to cover this functionality.

#359: Fix type casting logic for SET command.

---

core/dsql.go
core/dsql_test.go
core/eval.go
core/executor.go
core/push_response.go
go.mod
internal/constants/constants.go
server/async_tcp.go
tests/qwatch_test.go

This PR implements several improvements to the QWATCH functionality and adds JSON support:
1. Enhanced QWATCH response format:
- Added a `DSQLQuery.String()` method to serialize queries
- QWATCH responses now include the query string and "qwatch" identifier - in line with what newer clients expect.
- Updated tests to expect the new response format
2. Improved value comparison logic:
- Changed int comparisons to use int64 for consistency
- Updated compareIntValues function signature accordingly
3. Refactored QWATCH result encoding:
- Created a new `CreatePushResponse` function to standardize response format
- Updated both sync and async TCP handlers to use the new function
4. Minor improvements and fixes:
- Fixed some type assertions and comparisons in tests
- Updated existing QWATCH tests …

Fixes QWATCH response format, executor type inference logic, test cases

---

Makefile
core/bytelist.go
core/executor.go
core/io.go

I have added a make target for the linter and also provides the command to install the linter as suggest by [golangci-lint](https://golangci-lint.run/welcome/install/)
running `make lint` has made the changes we see in the modified files.
Also, currently the [linter **doesn't** run](https://golangci-lint.run/usage/configuration/#run-configuration) on the `test` files as configured in the `.golangci.yaml` file:
https://github.com/Maveric-k07/dice/blob/f2b1d3ae04e84c7ae1c00af8d03e049886ac8185/.golangci.yaml#L1-L9
And when i make the `tests: true` and run `make lint`; I see the following [output](https://gist.github.com/Maveric-k07/35e4bd26d8e5a1f3a16f39f3525988fb) while modifying 17 more files with comment changes, whitespace removal etc.
Let me know if we want to have the linter run on the …

adds make target for linter

---

core/eval.go
core/eval_test.go

hello，in JSON.TYPE command. there is some inconsistency with redis [JSON.TYPE](https://redis.io/docs/latest/commands/json.type/)
In Redis JSON.TYPE, such as below:
`
127.0.0.1:6379> JSON.SET user $ '{"name":"tom","flag":true,"high":1.75,"age":23,"test":null,"language":["java","python","go"], "parter":{"name":"jerry","flag":true}}'
127.0.0.1:6379> JSON.TYPE user
"object"
127.0.0.1:6379> JSON.TYPE user $
1) "object"
127.0.0.1:6379> JSON.TYPE user $.name
1) "string"
127.0.0.1:6379> JSON.TYPE user $.test
1) "null"
127.0.0.1:6379> JSON.TYPE user $.language
1) "array"
127.0.0.1:6379> JSON.TYPE user $.name
1) "string"
127.0.0.1:6379> JSON.TYPE user $..name
1) "string"
2) "string"
127.0.0.1:6379> JSON.TYPE user $.aaa
(empty array)
`
we could see. in reids.  JSON.TYPE returns an array of string …

fix:keep JSON.TYPE consistent with redis

---

core/commands.go
core/eval.go
core/eval_test.go
internal/constants/constants.go

hello:
this pr is link issue: #371 
including two commits:
1. feature: add support for command [JSON.CLEAR]  including integration test. refer to redis command:[json.clear](https://redis.io/docs/latest/commands/json.clear/)
2. refactor: modify the json.type. use lowcase for match dice code style.

#371: feat: add support for command [JSON.CLEAR] 

---

config/main.go
core/eval.go
core/executerbechmark_test.go
core/queueref.go
core/queueref_test.go
core/stackref.go
core/stackref_test.go

closes #285.
- Added a maximum limit for the number of stacks and queues.
- Added a maximum limit for stack size and queue size.
- Cleanup will remove expired and deleted keys, and it will be called every time Length is called.
- Added tests for the above points.

#285: Fix: STACKREFLEN and QUEUEREFLEN is not aware of the deletion of key 

---

core/diceerrors/diceerrors.go
core/eval.go
core/object.go
core/resp.go
tests/check_type_test.go

Addresses #411 
Added assertType for commands that are not applicable for SET Data structures.
* Design document, if any.
Commands related to STACKINT, Queue, BITs, GET were modified to return consistent messages.
* Information on any implementation choices that were made.
* Evidence of sufficient testing. You ``MUST`` indicate the tests done, either manually or automated.
existing test cases pass + added new test cases to check this behaviour.

#411: Add asserts checking non-set commands: addresses #411

---

core/eval.go
core/executerbechmark_test.go
core/executor.go
core/executor_test.go
core/query_watcher.go
core/queueref_test.go
core/resp.go
core/stackref_test.go
core/store.go
server/async_tcp.go
tests/qunwatch_test.go
tests/qwatch_test.go

Key changes:
- Extracted QWATCH logic into a new `QueryWatcher` struct.
- Moved `WatchList` from `Store` to `QueryWatcher`.
- Created `WatchSubscriptionChan` to handle subscribe/unsubscribe events.
- Updated `QWATCH` and `QUNWATCH` commands to use new channels.
- Refactored `ExecuteQuery` to take a pointer to `DSQLQuery`.
- Updated tests and benchmarks accordinly.

Move QWATCH logic to QueryWatcher

---

core/eval_test.go

- Create a new store for each iteration of the benchmark
- Ensures accurate performance measurement by starting with a clean state
- Prevents potential infinite loops or deadlocks caused by accumulated state
- Resolves issue with benchmark suite hanging indefinitely
Closes #385 
Ran test locally 
```
Running tool: /opt/homebrew/bin/go test -benchmem -run=^$ -bench ^BenchmarkEvalMSET$ github.com/dicedb/dice/core
goos: darwin
goarch: arm64
pkg: github.com/dicedb/dice/core
BenchmarkEvalMSET-10    	   50248	     22360 ns/op	  328741 B/op	      24 allocs/op
PASS
ok  	github.com/dicedb/dice/core	1.615s
```

#385: fix(benchmark): Reset store for each iteration in BenchmarkEvalMSET

---

core/dsql_test.go
core/eval.go
core/executerbechmark_test.go
core/executor.go
core/executor_test.go
core/query_watcher.go
core/store.go
internal/constants/constants.go
server/async_tcp.go
server/sync_tcp.go
tests/qwatch_test.go

This PR implements a caching mechanism for QWATCH queries to improve performance and reduce load on the main shard store.
1. Added a queryCache to store data relevant to each watched query, reducing the need to scan the entire store on each update.
2. Modified the QueryWatcher to maintain these caches, updating them as keys are modified.
3. Updated the QWATCH command to build the initial cache when a query is subscribed to.
4. Implemented an AdhocQuery channel and handler to execute queries against the cached data.
5. Updated the ExecuteQuery function to work with the new caching system.
6. Modified tests to work with the new caching system and added cleanup steps.
7. Added new constants for SET and DEL operations.
These changes should significantly improve the performance of QWATCH …

Implements caching for QWATCH queries to improve performance

---

core/bloom_test.go
core/eval_test.go
core/executerbechmark_test.go
core/executor_test.go
core/expire_test.go
core/main_test.go
core/query_watcher.go
core/queueref_test.go
core/shard_manager.go
core/shard_thread.go
core/stackref_test.go
core/store.go
server/async_tcp.go

There a cyclic dependency is being created between store and QueryWatcher.
This mainly caused as we initialize the QueryWatcher related global parameters as part of store initialization.
Without this change, it becomes difficult to separating out the worker/shard/QueryWatcher required for refactoring the code.
It also makes it difficult to refactor methods like `Encode()` in `resp.go` as the method references types from both `store` as well as `QueryWatcher` and QueryWatcher invokes the Encode() method creating a cyclic package dependency.

Remove query-watcher dependency from store

---

core/bitpos.go
core/dsql.go
core/dsql_test.go
core/executor.go
core/executor_test.go
tests/qwatch_test.go

This PR adds support for ordering query results based on JSON field values. This enhances the QWATCH feature to allow sorting of JSON objects.
1. Modified `DSQLQuery.String()` method to properly handle JSON fields in ORDER BY clauses.
2. Updated `ParseQuery()` and `parseOrderBy()` functions to support JSON path expressions in ORDER BY clauses.
3. Refactored `sortResults()` function in `executor.go` to implement JSON field-based sorting.
4. Added new comparison functions for various data types (int, int64, float64, bool).
5. Updated and expanded test cases to cover JSON ORDER BY scenarios.
- Modified the `getOrderByValue()` function to extract values from JSON fields using the specified path.
- Updated `compareOrderByValues()` to handle different data types that can be present in JSON …

Adds JSON support to ORDER BY clause for DSQL queries.

---

core/bitpos.go
core/executor.go
core/executor_test.go
internal/constants/constants.go

We were mixing up int and int64 types in the system, this PR fixes this inconsistency.

Fix integer type handling inconsistencies in sql executor

---

demo/leaderboard/Dockerfile
demo/leaderboard/README.md
demo/leaderboard/docker-compose.yaml
demo/leaderboard/go.mod
demo/leaderboard/go.sum
demo/leaderboard/index.html
demo/leaderboard/main.go

This demo showcases a real-time leaderboard application using DiceDB. Writing realtime applications with DiceDB is as simple as writing a single SQL query.
The application consists of two main components:
1. A Go backend that interacts with DiceDB and serves WebSocket connections.
2. A simple HTML frontend that displays the leaderboard in real-time.
The backend randomly generates player scores and updates them in DiceDB using a background thread. It then uses QWATCH to monitor changes and broadcasts updates to connected WebSocket clients.
1. Build and run the services using Docker Compose:
```
docker-compose up --build
```
2. Open a web browser and navigate to `http://localhost:8080` to view the leaderboard.
- `main.go`: The Go backend application
- `index.html`: The frontend HTML file
- …

Added realtime leaderboard demo using QWATCH

---

server/async_tcp.go

- When a client gets abruptly disconnected the server is logging warn messages currently. Since we don't have any connection/keep-alive checks in place for clients, server tends to ACK the connection and tries to read from buffer which leads to `net.ErrClosed`.
- We were already having check for `net.ErrClosed` which means connection has been closed from the client side and w can stop reading further. 
- Catch the error up the stack and just log `INFO` in such cases instead of `WARN` as it's an expected disconnection from client side.

Avoid logging WARN for disconnections initiated from clients

---

internal/eval/eval.go
tests/bit_ops_string_int_test.go
tests/bit_ops_string_test.go

Addresses https://github.com/DiceDB/dice/issues/412
Fixed bitmap related commands to work with strings and strings + bytearrays
Design document, if any.
Removed the optimization of resizing byte arrays in case the LSB is 0. This resulted in a deviation where a bit is set to 1 and then set back to 0. If the key to which this is set is the longest, the bitop commands return inaccurate results.
Additionally, GETSET was failing as we now handle returning byte arrays via GET. It turns out that the encoding constants are being reused even if they are different. In this case, the encoding value for deque and bytearray was 4. I have reshuffled the file contents for improved readability and possible changes in the values of the encoding to avoid collision in the future
existing test cases pass + …

#412: Bitmap commands: Fixed deviation from redis implementation

---

examples/leaderboard-go/main.go
internal/eval/bitpos.go
internal/querywatcher/query_watcher.go

This change adds a retry mechanism with exponential backoff to the client write logic of the `QueryManager`. This fixes undefined behavior in case of high number of writes.
Presently, if the QueryManager wrote too much data too fast to the client's socket it was possible to encounter a "resource temporarily unavailable) error.
The error "resource temporarily unavailable" (which typically corresponds to the `EAGAIN` or `EWOULDBLOCK` error codes) occurs when you're trying to write to a non-blocking file descriptor that currently can't accept more data. This usually happens when the client isn't reading data fast enough, causing the kernel's write buffer for that socket to fill up.
With the new changes, we check whether the client is only temporarily unavailable and implement a retry …

Adds retry with exponential backoff for QWATCH writes

---

internal/querywatcher/executor.go
internal/querywatcher/executor_test.go

This PR introduces support for `LIKE` and `NOT LIKE` string comparisons for the DiceDB SQL Executor.
This is necessary pre-work for the upcoming changes to the DSQL syntax which would rely purely on the WHERE clause for key filtering and not on the FROM clause.

Adds support for 'LIKE' and 'NOT LIKE' to the SQL Executor

---

config/config.go
internal/shard/shard_thread.go
tests/setup.go

Due to intermittent build failures on pipeline, we analysed the cause might be due to AOF dump taking long time and thus in turn tests were getting timed out leading to failure of build.
As part of this PR we've introduced a config `WriteAOFOnCleanup` to be used for testing env, which current case is being used to avoid AOF dump.

Adding TestEnvEnabled config and avoiding AOF dump for test env

---

internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

hello:
this pr is link  #484 
add json.arrlen command. refer to redis [json.arrlen](https://redis.io/docs/latest/commands/json.arrlen/)
add unit tests in eval_test.go
because JSON.ARRLEN never change the json value, so I think there is no need to add integration test in tests/json_test.go
the json.arrlen in redis behavior as below:
`
127.0.0.1:6379> JSON.SET user $ '{"age":13,"high":1.60,"pet":null,"language":["python","golang"],"flag":false,"partner":{"name":"tom","language":["rust"]}}'
OK
127.0.0.1:6379> JSON.ARRLEN user
(error) ERR Path '.' does not exist or not an array
127.0.0.1:6379> JSON.ARRLEN user $
1) (nil)
127.0.0.1:6379> JSON.ARRLEN user $.*
1) (nil)
2) (nil)
3) (nil)
4) (integer) 2
5) (nil)
6) (nil)
127.0.0.1:6379> JSON.ARRLEN user $..language
1) (integer) 2
2) (integer) 1 …

#484: feat: add support for command [JSON.ARRLEN]

---

internal/store/store.go

This change will help reduce our write latencies since the clients should not have to wait for auxiliary internal message passing before they receive a response.

Notifies Query Manager of key changes asynchronously

---

internal/errors/errors.go
internal/eval/eval.go
internal/eval/eval_test.go

The Dice server was breaking with the wrong `pfadd` command. 
This has been caught using TCL Redis tests.
Issue:
Fix:

Fixed hyperloglog type assertion check.

---

integration_tests/commands/json_test.go
internal/errors/errors.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

PR addresses #502 
Added support for `JSON.STRLEN`. added unit tests and integration tests
All tests passed.

#502 Added support for `JSON.STRLEN` 

---

internal/eval/eval.go

Closes #511 
Passes TCL Test
Passes existing dice tests
Working Example. (Changed port number to 6379 locally for running server)

SET with EX with big integer reports an error

---

.air.toml
Makefile
integration_tests/commands/hlen_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Closes #573 
Adds support for HLEN, matching the redis implementation. 
Attaching Benchmark results for the test here
[benchmark.txt](https://github.com/user-attachments/files/17001182/benchmark.txt)

#573: Added HLEN Support

---

internal/server/utils/redisCmdAdapter_test.go

Fixes issue : #581 
This PR fixes the following in the `TestParseHTTPRequest` test
1. Used `assert.ElementsMatch` which ignores the order of args and checks only if elements are present
2. Format test-cases for readablity

#581: fix: TestParseHTTPRequest 

---

integration_tests/commands/expire_test.go
integration_tests/commands/expireat_test.go
internal/errors/errors.go
internal/eval/bitpos.go
internal/eval/eval.go
internal/eval/eval_test.go
internal/server/utils/time.go
tmp/build-errors.log

The maximum TTL (Time to Live) in Redis is set to 9223372036854775 milliseconds, which is equivalent to approximately 106,751 days (or about 292 years). This value is based on the maximum possible value for a signed 64-bit integer (2^63 - 1), which is 9223372036854775807 milliseconds. Redis uses this value to represent TTLs internally. Redis stores TTL values in milliseconds. Therefore, the maximum value Redis can store for a TTL is constrained by the largest 64-bit signed integer.
Issues covered:
https://github.com/DiceDB/dice/issues/511
https://github.com/DiceDB/dice/issues/504
https://github.com/DiceDB/dice/issues/505
Evidences:

Added minimum and maximum Expiry time

---

integration_tests/commands/getdel_test.go
internal/eval/eval.go

#474 
I handled the set and JSON data type for GETDEL and am throwing an error if it is! 
Using getnotouch to retrieve the key based on the previous touch value! Decoding the value and returning based on its encoding type - int64, string, byte array.
Wrote manually the test cases with SetBit, Getdel, and get. Also, wrote a test case for getdel with set and the JSON object
Please review and let me know in case of questions or suggestions. @arpitbbhayani @JyotinderSingh @apoorvyadav1111

Enhance GETDEL to handle Set, JSON, and ByteArray, String, Integer and Expand Test Coverage

---

integration_tests/commands/qunwatch_test.go
integration_tests/commands/qwatch_test.go

Apologies for the long delay but the PR closes #408 
What was the issue?
* The where clause in queries was being built as an object which meant the `==` for DSLQuery object was failing. Hence we could not unsubscribe from a given query and concurrent writes were being sent to open client file descriptors.
* We were not cleaning up after SDK tests
* Qunwatch test did not stop watching on the final subscriber
What was the fix?
* Change the watchlist key to be the string representation of the query and parse back whenever required.
* PR #447 Introduced the SDK cleanup
* Qunwatch test not stops watching from all subscribers.
Scenario: (-> subscribe request, -x> unsubscribe request, c-i client with fd "i", <= resp from watcher)
Test - 1
c-1 -> q1
c-2 -> q2
c-1 -x>  q1 (here we expect cleanup …

QWATCH tests failing on multiple runs 

---

integration_tests/commands/json_test.go
integration_tests/commands/toggle_test.go

We should be comparing unmarshalled JSON strings instead of just the string representations.

Fix flaky JSON tests

---

integration_tests/commands/json_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Issue fixed : #499 
This PR introduces the new command `JSON.OBJLEN`
1. Implementation for JSON.OBJLEN ref: [RedisJSON](https://github.com/RedisJSON/RedisJSON/blob/master/redis_json/src/commands.rs) , [JSON.OBJLEN](https://redis.io/docs/latest/commands/json.objlen/)
2. Add unit tests
3. Add integration tests
4. Add benchmark
Dice DB(CLI demo)
Redis
1. Units tests
2. Integration tests
3. Benchmarks

#499: Add support for command JSON.OBJLEN

---

config/config.go
examples/leaderboard-go/docker-compose.yaml
integration_tests/commands/setup.go
internal/eval/eval_darwin_arm64.go
internal/eval/eval_linux_arm64.go
internal/shard/shard_thread.go

1. **AOF Persistence Configuration**
- Changed default `WriteAOFOnCleanup` to `true` in `config/config.go`
- Updated `integration_tests/commands/setup.go` to set `WriteAOFOnCleanup` to `false` for tests
- Modified cleanup logic in `shard_thread.go` to respect the `WriteAOFOnCleanup` configuration
2. **Architecture Support**
- Added support for Darwin ARM64 architecture with `eval_darwin_arm64.go`
- Renamed `eval_arm64.go` to `eval_linux_arm64.go` for clarity
3. **Docker Compose Update**
- Removed platform specification for AMD64 in `examples/leaderboard-go/docker-compose.yaml`

Add darwin arm64 compatibility

---

integration_tests/commands/copy_test.go
integration_tests/commands/json_arrpop_test.go
integration_tests/commands/json_test.go
internal/eval/eval_test.go
testutils/json.go

- Using `JSONEq` from [testify](https://pkg.go.dev/github.com/stretchr/testify/require#JSONEq) package for json comparisons. This would handle the ordering issues we're facing. For e.g. current test cases fails for scenarios like below where ordering of elements is changed.
`{"a":"b","b":[{"a":2.2},{"a":5},{"a":"c"}]} (out string) != {"b":[{"a":2.2},{"a":5},{"a":"c"}],"a":"b"} (result string)`
- One of the flaky builds log [here](https://productionresultssa18.blob.core.windows.net/actions-results/89060d43-0fce-4c1c-b438-727f7c4c1b7f/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text/plain&se=2024-09-17T14:27:48Z&sig=GAlQsKMGUqV2/2Vb6SQbzLwjU/eCNhNruoRZZzQ/gJM%3D&ske=2024-09-18T01:37:18Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-17T13:37 …

Fixing flaky unit test for JSON comparisons

---

integration_tests/commands/echo_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Resolves #622 : Add support for ECHO command.
- This  PR adds support for [ECHO](https://redis.io/docs/latest/commands/echo/) command to DiceDB.
- Added unit tests (internal/eval/eval_test.go)  
- Added integration tests (integration_tests/commands/echo_test.go)

#622: Add ECHO command

---

internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

Closes #644 .
This PR adds support for the `GETRANGE` command. It also adds tests from the TCL unit tests on redis. along with a basic benchmark test.
> [!NOTE]
> I skipped porting a [fuzz test from tcl](https://github.com/redis/redis/blob/3a3cacfefabf8ced79b448169319ce49cca2bfb7/tests/unit/type/string.tcl#L491) since it essentially reimplements the command logic in a test (our tests are also in go, so it seems redundand). Please let me know if i should port it or there is another approach to fuzz test it.

Add support for GETRANGE

---

.air.toml
config/config.go
internal/server/multitherading.go
main.go

```
❯ go run main.go --enable-multithreading=false 
{"level":"info","time":"2024-09-22T01:38:35+05:30","message":"Running server in single-threaded mode"}
{"level":"info","version":"0.0.4","port":7379,"time":"2024-09-22T01:38:35+05:30","message":"DiceDB is running"}
{"level":"warn","time":"2024-09-22T01:38:35+05:30","message":"DiceDB is running without authentication. Consider setting a password."}
{"level":"info","addr":":8082","time":"2024-09-22T01:38:35+05:30","message":"HTTP Server running"}
```

Add flag to enable/disable multi-threading on server

---

internal/logger/zerolog.go

Closes #685 
The new logger missed handling conversion of err values to the messages.

fix: log error messages instead of values 

---

internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go
internal/server/multitherading.go

- Currently HTTPServer was breaking in case of `PING` command as it was talking directly to shard and `executeCommandsToBuffer` is only implemented for `AsyncServer` to handle the `Global` defined commands.
- As for stop gap fix, so that HTTPServer doesn't break incase of `PING` command evaluation adding it back to `eval`.
- Going forward once the worker changes are done and we've a common layer for HTTPServer to interact with for executing all types of command i.e. `Global, SingleShard` etc. we'll remove this.
```
❯ curl --location --request POST 'localhost:8082/ping'
"PONG"
```
```
❯ redis-cli -h 0.0.0.0 -p 7379                                                                       
0.0.0.0:7379> ping
PONG
```

Reverting back evalPING command for HTTP server

---

internal/eval/eval.go

This PR attempts to close #663 however I realised rewrite would be a better option. This passes all tests under tcl (only for bitcount) and all integration tests. While this also fixes other issues, I don't want to overstep.
I've added comments wherever necessary but can elaborate wherever necessary
What has changed?
* Added better argument validation
* Changed counting in a loop to count using a bitmask
* Added better handling of start and end indices.
@lucifercr07 as mentioned, this does fix the other bitcount issues, lmk what you think. I believe this is a better way to fix the errors (fixing a single test would've made it messier if you get what I mean)
Happy to change the approach just to fix the single test.

#663: Fixed bitcount operations

---

integration_tests/commands/async/hdel_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

HDEL command implementation:
- Added input validation for minimum number of arguments
- Implemented deletion of multiple fields from a hash
- Added type checking to ensure the key is a hash
- Returns the count of successfully deleted fields
- Updates the store only if fields were actually deleted

#645 Add HDEL command

---

internal/eval/eval.go
internal/eval/eval_test.go

Fixes #666 
This pull request addresses the issue where the BITOP: BITOP with non string source key command in DiceDB was not giving the expected output
Fixed the error that must be shown correctly when running BITOP command with non string source key.
The expected output when the above set of commands when run on Redis:
The observed output Earlier was the above set of commands when run on DiceDB:

Fixes Inconsistent BITOP: BITOP with non string source key

---

internal/server/server.go
main.go

The startup statement related to multithreading has changed from debug to info with a more concise message.

fix startup statement

---

integration_tests/commands/async/bit_operation_test.go
internal/eval/commands.go
internal/eval/eval.go

This pull request addresses the issue where the `BITCOUNT` command in DiceDB was not validating that a key is passed along with the command leading to a runtime error in the server.
- Added Arity of -1 to the `BITCOUNT` command
- Added a check for the number of arguments in the `BITCOUNT` command to ensure at least 1 argument is provided
- The command returns an arity error when no argument is passed, consistent with Redis
- Added integration tests to validate the number of arguments

Fix: BITCOUNT no key provided

---

internal/eval/eval_darwin_arm64.go
internal/logger/zerolog.go

This PR fixes BGREWRITEAOF failing completely, Specifically for MacOS for now .
The root cause is that macos doesn't set `pid` to `0` for child process
The solution is to record get original pid of main process and do `isChild := syscall.Getppid() == originalPID`. The `pid == 0` check is unreliable and breaks on maocs m2 in my testing.
This PR also adds logging features and a bit of refactoring to reuse code and allow for `logger.With(...attrs)` to be logged correctly

Fix Child Process not working for BGREWRITEAOF on MacOS + Logging Improvements

---

internal/eval/commands.go
internal/eval/constants.go
internal/eval/eval.go

Resolves #635 -  Command Subcommands should be listed as separate commands
This PR adds the sub-commands of `COMMAND` to the list of commands displayed on `COMMAND LIST` command.

#635: List Command Subcommands as separate commands

---

internal/shard/shard_manager.go

This goroutine was running and spinning up, and no functionalities were getting performed.

Removed unwanted goroutine

---

integration_tests/commands/async/bit_operation_test.go
internal/eval/bitpos.go

Fixed BITPOS command

---

integration_tests/commands/http/get_test.go
integration_tests/commands/http/getdel_test.go
integration_tests/commands/http/getex_test.go
integration_tests/commands/http/getset_test.go
internal/server/utils/redisCmdAdapter.go

FIxes #738 
This pull request adds the Http Integration Tests for GET, GETDEL, GETEX, GETSET commands.

#738: Added Http Integration Tests: Create tests to support for GET, GETDEL, GETEX, GETSET commands

---

docs/astro.config.mjs
docs/src/content/docs/commands/QWATCH.md
docs/src/content/docs/get-started/connecting-to-dice.mdx
docs/src/content/docs/protocols/http.mdx
docs/src/content/docs/protocols/websockets.mdx

Closes #559 
NOTE: - we should flag all commands that are not supported over http/websocket. do we have a list of them? i've only added the flag for QWATCH over Websocket

#559: docs: docs for protocols

---

internal/eval/eval_linux_arm64.go

Fixes #762 
Verification steps
```bash
~/dice fix/762_linux_arm_support !1 ?1 > git commit -a -m "Defined config file def and returning nil"                                                                                                                                23:32:02
[fix/762_linux_arm_support a12808a] Defined config file def and returning nil
1 file changed, 2 insertions(+), 1 deletion(-)
~/dice fix/762_linux_arm_support ?1 > GOARCH=arm64 GOOS=linux go build -o dice-arm64 main.go                                                                                                                                         23:32:06
~/dice fix/762_linux_arm_support ?1 > go build -o dice main.go …
```

#762: Defined config file def and returning nil

---

internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go
internal/eval/hmap.go

Closes #648 
This PR adds support for the `HINCRBYFLOAT` command. It also adds unit tests and a basic benchmark test.

#648: feat: adding HINCRBYFLOAT command implementation

---

integration_tests/commands/async/json_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

hello:
this pr is link issue: #490 
feature: add support for command [JSON.ARRTRIM] including integration test. refer to [redis.arrtrim](https://redis.io/docs/latest/commands/json.arrtrim/)
In redis. the JSON.ARRTRIM act as below:
`
127.0.0.1:6379> JSON.SET user $ '{"connection":{"wireless":true,"names":["a","b","c","d","e"]},"price":99.98,"stock":25,"colors":["black","silver"],"names":[0,1,2,3,4,5,6]}'
OK
127.0.0.1:6379> JSON.ARRTRIM user $ a 3
(error) Couldn't parse as integer
127.0.0.1:6379> JSON.ARRTRIM user123 $ 0 3
(error) ERR could not perform this operation on a key that doesn't exist
127.0.0.1:6379> JSON.ARRTRIM user $.names 1 4
1) (integer) 4
127.0.0.1:6379> JSON.GET user
"{\"connection\":{\"wireless\":true,\"names\":[\"a\",\"b\",\"c\",\"d\",\"e\"]},\"price\":99.98,\"stock\":25,\ …

#490: feat:add support for command [JSON.ARRTRIM]

---

DOC.md

Closes : [#720 ](https://github.com/DiceDB/dice/issues/720)
Issue was that command to run storm was mentioned as `$ go run storm/set/main.go` , this leads to :
```
go: downloading go1.23.0 (linux/amd64)
stat storm/set/main.go: no such file or directory
```
Now fixed, 
Changes :
Changed command mentioned in DOC.md to run storm from `$ go run storm/set/main.go` to `$ go run storm/set/set.go`

changed file name in DOC.md to run storm from main.go to set.go

---

internal/eval/eval.go
internal/eval/eval_test.go

Hi team,
While reviewing the code for any issues/bugs, I observed that the type command returns strings as BULK instead of simple. It is a small change and related tests have been updated as well.
Fixes: #862
Thanks

#862: Fixes TYPE command return encoding

---

Makefile

Fixes https://github.com/DiceDB/dice/issues/855 
This fix uses environment environment variables to get the different architecture and Operating system and avoids the usage of default linux build.
Additionally, 
1. Added `help` command to see the make options available.
2. Added `clean` command to clean the build artifcats.

#855: Make DiceDB build work on different architectures

---

README.md

While setting up the Dice DB on my local machine, I noticed that the README file doesn’t include the full Docker command to run it on port 7379. To address this, I’ve updated the README in this PR.

update readme with adding port in the docker command

---

internal/eval/hmap_test.go

Closes #874 
Adding unit tests for `internal/eval/hashmap` implementation along with the helper functions.

#874: adding unit tests for hash map implementation and helper functions

---

docs/src/content/docs/commands/PING.md

This PR resolves https://github.com/DiceDB/dice/issues/773
- Refactored headings to match as per syntax requirement in issue https://github.com/DiceDB/dice/issues/773
- Refactored formatting for Parameters, Return values  , Examples sections
- Added 127.0.0.1:7379> in all CLI implementation examples
- Refactored cli output error messages to reflect current CLI error message syntaxes in Examples and Errors sections
- Refactored Examples section to include examples of different values

#773: Update PING cmd Docs

---

docs/src/content/docs/commands/JSON.DEL.md

- Added missing syntax section for `JSON.DEL` in documentation.
- Updated formatting by referring [SET Command docs](https://dicedb.io/commands/set/)
- Updated examples to use `$` for path demonstration instead of `.` to align with Redis behavior (dicedb works fine with `.` but redis throws error `the legacy path syntax is not supported. JSONPath must start with $`).
- Improved error message documentation for wrong types during `JSON.DEL`. DiceDB shows `ERROR Existing key has wrong Dice type`, while Redis shows `WRONGTYPE Operation against a key holding the wrong kind of value`. (this should be consistent)
(for redis instance upstash was used)
Fixes #842

fix(json.del): add missing syntax, update example path & error message

---

docs/src/content/docs/commands/PFCOUNT.md

fixes #793 
1. Created markdown tables for `Parameters` and `Return Values`
2. Updated CLI prompt to `127.0.0.1:7379>`
3. Changed order of headings according to `SET` command

docs: improve consistency in PFCOUNT documentation

---

integration_tests/commands/resp/main_test.go
integration_tests/commands/resp/setup.go

Seeing some flakiness in test server startup.
Starting the test server on port 8739
{"level":"error","error":"address already in use","time":"2024-10-02T23:20:35+05:30","message":"Error occurred"}
{"level":"error","error":"failed to bind socket: address already in use","time":"2024-10-02T23:20:35+05:30","message":"failed to bind server"}
{"level":"error","error":"failed to bind socket: address already in use","message":"Test server encountered an error"}
FAIL    github.com/dicedb/dice/integration_tests/commands/resp  2.416s
Changed RESP test server port to 9739 to avoid port conflicts with ASYNC server.

Change port for RESP server integration tests

---

integration_tests/commands/http/json_arrpop_test.go
integration_tests/commands/http/json_test.go
integration_tests/commands/http/keys_test.go
integration_tests/commands/http/mget_test.go
integration_tests/commands/http/mset_test.go
internal/server/utils/redisCmdAdapter.go
internal/server/utils/redisCmdAdapter_test.go

Fixes #741
- Added integration tests for KEYS, MGET, MSET, JSON commands using HTTP
- Added `json` and `index` to priorityKeys at [redisCmdAdapter.go](https://github.com/DiceDB/dice/blob/master/internal/server/utils/redisCmdAdapter.go#L76). `index` was added to support commands with index in the arguments. `json` was added to support `JSON.SET`  with `nx` and `xx` flag, as `json` needs to be parsed before those flags.

#741: Add integration tests for KEYS, MGET, MSET, JSON commands using HTTP

---

docs/src/content/docs/commands/JSON.CLEAR.md

Audit documentation for JSON.CLEAR and make it consistent with the existing implementation.
[https://github.com/DiceDB/dice/issues/772](https://github.com/DiceDB/dice/issues/772)
- Attempted to follow documentation format in [SET](https://dicedb.io/commands/set/)
- Found some discrepancies in `## Behaviour` section which i changed.
- Fixed few things in the `## Errors` section.

#772: Audit and make documentation for command JSON.CLEAR consistent

---

internal/sql/dsql.go
internal/sql/fingerprint.go
internal/sql/fingerprint_test.go

This PR implements generating same fingerprint for logically same WHERE clause of a DSQL query.
Expression in WHERE clause of DSQL can be representated in boolean algebra.
`$key like 'match:1:*' AND $value > 100` can be representated as `A AND B`. With this approach we can simplify complex boolean algebra into its simplified version using [laws of boolean algebra](https://en.wikipedia.org/wiki/Boolean_algebra#Laws).
Example
`$key like 'match:1:*' AND $value > 100` and `$value > 100 AND $key like 'match:1:*'` are logically same.
We represent each comparison expression(`$key like 'match:1:*'`) in form _operator + leftOperand + rightOperand_, then this can be assumed as `A` in boolean algebra representation.
Now each comparison expression can be considered as an operand, then we sort these …

#548: feature: query fingerprinting

---

docs/src/content/docs/commands/RPOP.md

#817: docs: improve consistency in RPOP documentation

---

docs/src/content/docs/commands/SINTER.md

Fix #808 
Please merge this PR after #906 (add support for SINTER cmd single key parameter) to maintain consistency between docs and implementation.
- Update description
- Change the Parameters, Return values section to tabular format
- Remove the example - intersection with empty set. (Create empty set cmd doesn't work, i.e., `SADD set3`) - non-existent set is by-default treated as empty set.
- CLI input prompt is prefixed with `127.0.0.1:7379>`

#808: docs: modified SINTER

---

config/config.go
main.go

Allows users to customize the KeysLimit value at server start improving control over memory allocation and preventing previous runtime out-of-memory issues.

fix: Allows users to customize the KeysLimit value at server start

---

internal/eval/hmap.go
internal/eval/hmap_test.go

#921: Added Hashmap incrementFloatValue overflow check

---

docs/src/content/docs/commands/DECRBY.md

Docs:Updated DECRBY Docs #780

---

integration_tests/commands/async/del_test.go
internal/eval/eval.go
internal/eval/eval_test.go

FIX: Delete Command with 0 Arguments

---

docs/src/content/docs/commands/HSCAN.md
go.mod
go.sum
integration_tests/commands/async/hscan_test.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go

- Added HSCAN command to iterate over hash fields and values
- Implemented cursor-based iteration and glob pattern matching
- Added unit tests
- Added integration tests
- Added doc for HSCAN command
Issue: #653

#653: Added HSCAN command

---

docs/src/content/docs/commands/SCARD.md

This PR fixes #790 
- Updated the titles to match the `strings` as specified in the [issue](https://github.com/DiceDB/dice/issues/790) .
- Created markdown tables for `Parameters` and `Return Values`
- Re-order the pointers in `Behaviour` section to be aligned with `Return values` section.
- Reformatted `Errors` section and added a new error
- Updated CLI prompt to 127.0.0.1:7379>
- Added a new Error Example for `Wrong Argument`

Audit and make documentation for command SCARD consistent 

---

docs/src/content/docs/commands/GETBIT.md

docs: Add Arity Error Documentation to GETBIT

---

integration_tests/commands/async/append_test.go
integration_tests/commands/async/deque_test.go
integration_tests/commands/async/getset_test.go
integration_tests/commands/async/type_test.go
integration_tests/commands/http/getset_test.go
integration_tests/commands/http/type_test.go
integration_tests/commands/resp/getset_test.go
internal/eval/eval.go

replaced the OK message shown after the LPUSH and RPUSH by the size of deque similar to the output in redis

fix:  Deque-push-output

---

integration_tests/commands/async/qunwatch_test.go
integration_tests/commands/async/qwatch_test.go
integration_tests/commands/http/set_data_cmd_test.go

Closes #188 
This PR
1. adds integration tests for QWATCH Where clause
2. adds tests for both JSON and Regular keys
3. refactors existing code to reuse helper functions
4. fixes a flaky test case in `TestSetDataCmd`

#188: Added Integration Tests for QWATCH Where Clause

---

integration_tests/commands/resp/getwatch_test.go
integration_tests/commands/resp/zrangewatch_test.go
internal/eval/eval.go
internal/store/constants.go
internal/watchmanager/watch_manager.go
internal/worker/cmd_meta.go

This PR adds support for the ZRANGE.WATCH command, allowing clients to watch for changes to sorted sets. The main changes include:
1. New integration test for ZRANGE.WATCH command
2. Added ZAdd and ZRange constants in store/constants.go
3. Updated watchmanager to support ZRANGE.WATCH
4. Added ZRANGE.WATCH command metadata
5. Modified ZADD command to use the WithPutCmd option to properly track the changes.
Both raw RESP protocol and SDK-based tests are included to ensure compatibility.

Adds support for ZRANGE.WATCH

---

internal/eval/eval.go
internal/eval/eval_test.go

Fixes #995 
Now the return is correctly configured to 0 when key exists but no expiration is set on it.

Fix return value in evalPersist function(when key exists but no expiration is set on it)

---

docs/src/content/docs/commands/JSON.GET.md
integration_tests/commands/async/json_test.go
internal/eval/eval.go

1. Return error when JSON path does not exists in the JSON data stored against a key (making it consistent with Redis)
2. Error format : `(error) ERR Path '$.<path>' does not exist`
Closes https://github.com/DiceDB/dice/issues/955

#955: fix: JSON.GET should return error when JSON path does not exist in JSON data

---

docs/src/content/docs/commands/LPOP.md

- Fixes #828 
During the audit, I also discovered that the LPOP command does not support the `COUNT` parameter, which differs from the behavior of [Redis's LPOP](https://redis.io/docs/latest/commands/lpop/). Is this feature pending implementation? If so, I would be interested in working on it.
Thank you!

#828: Audit and make documentation for command lpop consistent

---

integration_tests/commands/async/json_test.go
internal/eval/eval.go

This will fix the issue where, instead of completely removing an element from the array and reindexing, we get `null` when we try to forget the element.
Fixes #910

fix null value in removing array element and add test for this scenario

---

integration_tests/commands/async/json_test.go
internal/errors/errors.go
internal/eval/commands.go
internal/eval/eval.go
internal/eval/eval_test.go
internal/object/typeencoding.go

Fixes #501 
This pull request adds support for JSON.STRAPPEND command

Add support for command JSON.STRAPPEND #501

---

internal/errors/migrated_errors.go
internal/eval/eval_test.go

@lucifercr07 @JyotinderSingh Please review and merge. This is an urgent fix before migration of evals.

Make error statements similar to the redis, in migrated errors 

---

docs/src/content/docs/commands/PFMERGE.md

This PR aims to find and fix inconsistencies in the documentation for the `PFMERGE` command as mentioned in the issue #798 
The objectives of this PR can be simplified in the points below
end goal - documentation should match the format followed by [SET](https://dicedb.io/commands/set/) and be consistent with how the code works 
Fixes #798

Issue 798 - Auditing PFMERGE command docs

---

internal/server/server.go

#1070: Fixes Async Server when incorrect command leads to inconsistent output

---

Dockerfile
README.md
config/config.go

This PR makes dev mode logging the default.
This PR also makes sure that the dockerifle is built with prod mode logging

fix: switch logging mode to dev by default

---

README.md

#Problem 
- When copying the commands using the clipboard action button, $ also gets copied. This behavior hinders Readme file usage.
#Solution
- Removed $ from the bash/shell/sh command snippets.
- Marking every command snippet uniformly with bash.

Optimized Readme for clipboard copy action.

---

config/config.go
integration_tests/commands/websocket/setup.go
integration_tests/commands/websocket/websocket_write_retries_test.go
internal/server/websocketServer.go

Fixes: #717 
the following failure scenarios have been added
Timeout: Check if net.Error and checking if it's a timeout.
Retries: Exponential backoffs and retries in writes
Connection reset: Detect by checking for syscall.ECONNRESET
Broken Pipe: Detect broken pipe by using syscall.EPIPE

fix: handling multiple failure/error scenarios during socket writes

---

docs/src/content/docs/commands/BITCOUNT.md

- Reformatted the documentation
- Validated all the examples and fixed an incorrect output value
- Added missing parameter details to make it consistent with the code

#838 Update/fix the documentation for BITCOUNT command

---

.air.toml
config/config.go
main.go

This PR adds profiling support for DiceDB
How to run profiling:
```
go build main.go  
./main --enable-multithreading=true --enable-profiling=true
```

Add profiling for DiceDB

---

docs/src/components/Footer.astro
docs/src/components/Hero.astro

Hi team,
DiceDB has recently crossed 6000 stars (currently 6.2k+). This PR updates this stat on dicedb.io. 
Thanks,
Apoorv

Update: GitHub stars on docs

---

integration_tests/commands/async/append_test.go
internal/eval/eval.go
internal/eval/eval_test.go

Fixes #1101 
evalAPPEND function wasn't configured to handle the case with leading zeros and it is treating value "0043" as "43"
I have added that case to handle it properly and producing desired result as of redis

#1101: Refactor evalAPPEND to handle leading zeros in value

---

docs/src/content/docs/protocols/http.mdx

#1113
1. Added Curl Examples to HTTP Docs. For Better DX.
2. Fixed Response which we actually get from the calls. 
Attaching screenshots for the same.
Incase of any changes please let me know.
cc @JyotinderSingh

#1113 Add cURL Examples to HTTP Docs

---

docs/src/content/docs/protocols/websockets.mdx

#1113 
1. Followed similar styling found in HTTP docs using tabbed examples
2. Included example of interacting with the websocket via [`wscat`](https://github.com/websockets/wscat)

#1113 docs: add CLI example to websocket

---

internal/clientio/iohandler/netconn/netconn.go
internal/worker/worker.go

Changed log level for connection close events to Debug.

Set conn close log level to debug

---

integration_tests/commands/websocket/get_test.go
integration_tests/commands/websocket/helper.go
integration_tests/commands/websocket/hyperloglog_test.go
integration_tests/commands/websocket/json_test.go
integration_tests/commands/websocket/main_test.go
integration_tests/commands/websocket/set_test.go
integration_tests/commands/websocket/setup.go
integration_tests/commands/websocket/writeretry_test.go
internal/server/websocketServer.go
main.go

This PR fixes following issues:
1. Several `Error reading from client` errors were thrown while running Integration tests because client disconnection was not handled and server kept trying to read. Added error handling of `acceptable errors` and added a warning for other errors. Any kind of error received now returns the `WebsocketHandler` function.
2. Several `Error writing response` errors were thrown while running Integration tests because some of the test commands were not written to also read response from server. Created two different functions `FireCommand` and `FireCommandAndReadResponse`. Refactored existing tests to run correctly.
3. Migrates assert to testify/assert
4. A few other minor fixes

Fixed bugs in Websocket Integration Tests

---

docs/command_docs_template.md
docs/sample_command_docs.md

Hi team,
Added an empty .md file for command docs based on `SET` documentation. It is to be used by contributors for auditing and added documentation.
Thanks
Apoorv

Added template for command docs

---

integration_tests/commands/http/json_arrpop_test.go
internal/server/httpServer.go

- Refactor `writeResponse` method to segregate migrated response handling
- Added support for parsing `[]interface{}` as part of `EvalResponse`
- Added integration tests

Refactor HTTP response

---

docs/src/content/docs/commands/QWATCH.md

Fixes [QWATCH audit and doc update](https://github.com/DiceDB/dice/issues/781).
- Refactor using [SET Command docs](https://dicedb.io/commands/set/) as reference
- Use $ for path demonstration instead of .

#781: Audit `QWATCH` documentation for consistency

---

internal/eval/eval_test.go

Hi team,
These print statement floods the log when unit tests fail and thus make the logs difficult to understand.
Thanks
Apoorv

Fix: removed extra prints in unit test

---

integration_tests/commands/http/zrank_test.go
integration_tests/commands/resp/zrank_test.go
integration_tests/commands/websocket/zrank_test.go
internal/eval/eval_test.go
internal/eval/store_eval.go

fixes #1165 
ZRANK when used with WITHSCORE now return score as string

#1165: Fix ZRANK command to return score as string with WITHSCORE

---

internal/server/websocketServer.go

The identification of broken pipe is only when there is an abrupt exit, so what I saw in the codebase was there are only a couple of places that deal with the closure of WebSocket connections, most of them were only handling the case where the user exited irrespective if it was gracefully or abruptly, so I modified and added some sections for the same
- in the `closing_handshake` , it wasn't checking if the closeValue had an error, indicating that there was an error while closing the connection, so I added a check for the same
- now when a message is being read, if there is an error that belongs to the `errs` category, it means that there is a graceful exit, otherwise, the exit was due to another error, so I have added the check for the same
- In the `WriteResponseWithRetries` you have a …

Issue-1103 - Fixing broken pipe errors

---

internal/server/utils/redisCmdAdapter.go
internal/server/utils/redisCmdAdapter_test.go

The PR closes #1191.
Changes made:

#1191 Refactor WebSocket Parser to support values with spaces

---

docs/src/content/docs/commands/SMEMBERS.md

@apoorvyadav1111 @JyotinderSingh Few pointers that need to be addressed.
Alternate Commands such as 
SSCAN but right now it is not not in DICE-DB should i remove all of its Reference in the DOC for now?

 #800 Smember DOCS Consistency

---

docs/src/content/docs/commands/HLEN.md
docs/src/content/docs/commands/HSCAN.md
docs/src/content/docs/commands/HSTRLEN.md
docs/src/content/docs/commands/ZCARD.md
docs/src/content/docs/commands/ZREM.md

Fixes inconsistencies in documentations of HLEN/HSTRLEN/HSCAN/ZCARD/ZREM commands (all migrated).
closes #806

#806: Fix documentations of HLEN/HSTRLEN/HSCAN/ZCARD/ZREM

---

integration_tests/commands/async/object_test.go
integration_tests/commands/http/hdel_test.go
integration_tests/commands/http/hget_test.go
integration_tests/commands/http/hset_test.go
integration_tests/commands/http/hvals_test.go
integration_tests/commands/http/json_test.go
integration_tests/commands/websocket/hdel_test.go
integration_tests/commands/websocket/hget_test.go
integration_tests/commands/websocket/hset_test.go
internal/eval/eval_test.go

Adds missing integration tests for HSET/HGET/HDEL migrated as part of #1021

#1021 : Add integration tests for HSET/HGET/HDEL

---

.github/workflows/cve-scan.yml
.github/workflows/dockerhub.yml
.github/workflows/full-test-suite.yml
.github/workflows/linter.yml
main.go

Hi @JyotinderSingh 
I have made some changes as per the disccusion on issue:
- https://github.com/DiceDB/dice/issues/620
Changes:
1. The **dockerhub.yml** is going to cache layers to resuse. I have some questions around this one.
Since I see this CI will only trigger on release it means frequency will be less. I have added the changes, but couldn't test it. Please go through it once, then we can talk more on it.
2. The **full-test-suite.yml** is going to cache the go dependencies from last build. Only pull new if required. Now I see Suryavir has very well defined to ignore the files **when not to run** the CI. We can make it **run only on** changes to go files or go.mod. Because with time, my understanding is that new folders and types of files may be included.
3. The **linter.yml** now …

A Better CI

---

docs/src/data/benchmarks.md

This pull request includes a small change to the `docs/src/data/benchmarks.md` file. The change corrects a typo by replacing "meatier" with "memtier".

Fix typo in benchmarks.md

---

docs/src/content/docs/commands/SET.md
integration_tests/commands/http/bloom_test.go
integration_tests/commands/http/set_test.go
integration_tests/commands/resp/append_test.go
integration_tests/commands/resp/bloom_test.go
integration_tests/commands/resp/getunwatch_test.go
integration_tests/commands/resp/getwatch_test.go
integration_tests/commands/resp/set_test.go
integration_tests/commands/resp/setup.go
integration_tests/commands/websocket/bloom_test.go
integration_tests/commands/websocket/set_test.go
internal/eval/eval_test.go
internal/eval/store_eval.go

Hi team,
Fixes: #207 
Added support for GET option in SET.

#207 Feature: get in set

---

internal/clientio/resp.go
internal/clientio/resp_test.go

Adds fix for RESP parser to parse string containing multiple `\r` until it encounters the first `\r` immediately followed by a `\n`.
Fixes #1245 and unblocks #1089

#1245: Fix RESP parser to parse strings with multiple \r

---

integration_tests/commands/http/zset_test.go
integration_tests/commands/resp/zset_test.go
integration_tests/commands/websocket/zset_test.go
internal/eval/constants.go
internal/eval/eval.go
internal/eval/store_eval.go
internal/store/constants.go
internal/watchmanager/watch_manager.go

I have implemented Redis's option parsing for the ZADD command. Additionally, I wrote unit and integration test cases to cover the functionality.
@apoorvyadav1111 Please review this and let me know if any modifications are needed. Thank you!
I added the evaluated command logic, which handles ZADD based on option flags and operates according to the Redis source code. I also created the zset_test file for HTTP, web socket, and resp, which contains test cases for the command with various combinations of options.
Fixes #761
Closed PR related to the above https://github.com/DiceDB/dice/pull/1138
The existing open PR for this issue is https://github.com/DiceDB/dice/pull/1205 (the reason I have created a new PR is because of a messed up history in PR 1138).
Will put the documents in the other …

#761: Added ZADD options implementation - XX|NX|CH|INCR| LT|GT according to Redis source code

---

docs/src/content/docs/commands/GETRANGE.MD
integration_tests/commands/http/getrange_test.go
integration_tests/commands/resp/getrange_test.go
integration_tests/commands/websocket/getrange_test.go
internal/eval/eval_test.go
internal/eval/store_eval.go

Enhances [GETRANGE](https://redis.io/docs/latest/commands/getrange/) to support byte array.
PR Checklist
closes https://github.com/DiceDB/dice/issues/1194

#1194: Enhance GETRANGE to support byte array

---

docs/src/content/docs/commands/APPEND.md
integration_tests/commands/http/append_test.go
integration_tests/commands/resp/append_test.go
integration_tests/commands/websocket/append_test.go
internal/eval/eval_test.go
internal/eval/store_eval.go

PR adds bytearray/bitmap support to [APPEND](https://redis.io/docs/latest/commands/append/) commands to match with REDIS behaviour.

Enh: Add bytearray support to APPEND

---

docs/src/content/docs/commands/ZADD.md
integration_tests/commands/http/zset_test.go
integration_tests/commands/resp/zset_test.go
integration_tests/commands/websocket/zset_test.go
internal/eval/store_eval.go

1. I have added Docs to ZADD Command.
2. Updated the error messages to match it to the Redis Error messages to make it consistent.
#1283

#1283: Feat: ZADD Docs and Error Messages

---

.gitignore
internal/clientio/iohandler/netconn/netconn.go
internal/clientio/iohandler/netconn/netconn_resp_test.go
internal/clientio/iohandler/netconn/netconn_test.go
internal/worker/worker.go

The IOHandler code is refactored for the following:
1. Better readability
2. More Robust error handling
3. CPU and Memory optimisations

Refactor IOHandler code

---

integration_tests/commands/resp/append_test.go
integration_tests/commands/resp/bit_test.go
integration_tests/commands/resp/getunwatch_test.go
integration_tests/commands/resp/getwatch_test.go
integration_tests/commands/resp/main_test.go
integration_tests/commands/resp/pfcountwatch_test.go
integration_tests/commands/resp/set_data_cmd_test.go
integration_tests/commands/resp/set_test.go
integration_tests/commands/resp/setup.go
integration_tests/commands/resp/zrangewatch_test.go
integration_tests/commands/resp/zset_test.go
internal/worker/worker.go

This PR fixes a bunch of issues.
First, it fixes goroutine leaks in worker by adding a ctx ub child goroutine to exit if parent is exits. See #1297 for more details.
Second, there were additional goroutine leaks because of `initHealthCheck` goroutine (`watch_connection.go`) in SDK. This was because `WatchConn` was not closed in any of the tests, only `Clients` were closed. `WatchConn.Close()` sends closing signal to this goroutine. This is fixed by making helper functions `ClosePublisherSubscribers`  and `ClosePublisherSubscribersSDK` which close it properly and make is easier for other developers to not worry about it going forward.
Third, none of the tests unsubscribe as part of cleanup. Hence, watch manager keeps sending updates to buffered channel `AdhocChannel` which has a configured …

Fixed goroutine leaks and deadlocks in Worker and Resp Integrations Tests

---

Makefile

This pull request includes significant changes to the `Makefile` to improve the organization and clarity of the available commands. The changes primarily focus on restructuring the help commands and adding descriptions for each make target.
* Changed the default goal to `help` and added a formatted help command to display available targets and their descriptions.
* Grouped targets into categories (Helpers, Building, Testing, Benchmarking, Development) and added descriptions for each target. [[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L17-R55) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L92-R96)
* Added new targets for running the project (`run`, `run-docker`)

refactor makefile

---

integration_tests/commands/http/append_test.go
integration_tests/commands/resp/append_test.go
integration_tests/commands/websocket/append_test.go
internal/eval/store_eval.go
internal/eval/type_string.go

- Resolved an issue where the TTL was incorrectly reset to -1 after using the APPEND command on a key with an existing TTL.
- The TTL is now correctly preserved after appending to a key, matching expected behavior in Redis.
- Added relevant test cases to ensure that TTL is maintained across APPEND operations.
- Tests include scenarios for key expiration after APPEND and correct TTL decrement over time.
Closes #1036

#1036 Preserve TTL after APPEND command

---

integration_tests/commands/resp/command_docs_test.go
internal/eval/commands.go

Issue:
- `redis-cli` expects `COMMAND DOCS` response to be in a particular [structure](https://redis.io/docs/latest/commands/command-docs/)
Fix:
- Modified `COMMAND DOCS` to be in sync with the expected format. We'd need to add more metadata to commands to support all the keys as part of commands mapped reply.
Output with redis-cli:

#1207 Fix redis-cli connect error

---

config/config.go
integration_tests/config/parser_test.go
internal/cli/cli.go

Issue:
- `enable-wal` flag is not adhered/used anywhere hence passing that doesn't affect persistence config.
Fix:
- Replaced `enable-wal` with `enable-persistence`(already present config)
Output:
```
❯ go run main.go  --enable-persistence=false
2024-11-22T11:41:17+05:30 INF Field Logging.LogDir failed validation: dirpath
2024-11-22T11:41:17+05:30 INF Setting default value for Logging.LogDir to: /tmp/dicedb
██████╗ ██╗ ██████╗███████╗██████╗ ██████╗ 
██╔══██╗██║██╔════╝██╔════╝██╔══██╗██╔══██╗
██║  ██║██║██║     █████╗  ██║  ██║██████╔╝
██║  ██║██║██║     ██╔══╝  ██║  ██║██╔══██╗
██████╔╝██║╚██████╗███████╗██████╔╝██████╔╝
╚═════╝ ╚═╝ ╚═════╝╚══════╝╚═════╝ ╚═════╝
2024-11-22T11:41:17+05:30 INF starting DiceDB version=0.1.0
2024-11-22T11:41:17+05:30 INF running with port=7379 …
```

Fix to adhere enable persistence flag when passed as program args

---

Makefile
README.md

- Added a reference guide on well-documented Makefiles.
- Moved the `release` target to a new `Deployment` section for better organization.
- removed outdated readme content

fixed makefile and removed outdated content from readme

---

docs/src/content/docs/commands/GETRANGE.md

@apoorvyadav1111  the documentation was present. The file extension was capital because of which it was not recognized as a valid page. I just changed the extension. I kept the file content as it is.

GETRANGE markdown file not detected as the extension was in capital

---

integration_tests/commands/resp/getwatch_test.go
internal/watchmanager/watch_manager.go

- Issue:
When we fire the `unwatch` command once the client exits watch mode, observed that fingerprint gets removed from `querySubscriptionMap` even if other clients are still subscribed to that query. If there's clients still subscribed to same query i.e they've entry in `tcpSubscriptionMap[fingerprint]` we shouldn't delete the fingerprint as further changes to the key won't be delivered to the clients.
- Steps to reproduce:
1. Connect 2 clients to get.watch k1
2. Disconnect 1 client
3. Execute set k1 v2, doesn't get delivered to other client still in watch mode.
Fix:
- Only remove it from the map if the query subscribed client list is empty
- Added integration test for the same
Fix working locally:

Fix unwatch for client unsubscribe when multiple clients subscribed to same query

---

integration_tests/commands/http/append_test.go
internal/eval/bytearray.go

This PR closes issue #1115:
- Updated `ByteSliceToObj` function to handle integer parsing more robustly. If the modified byte array can't be parsed as an integer, it now defaults to a string format(similar to how redis handles it).
- added corresponding unit test with expected output.

fix: issue #1115 handling integer parsing in SETBIT in certain situation

---

docs/src/content/docs/commands/JSON.OBJKEYS.md
docs/src/content/docs/commands/JSON.OBJLEN.md

Created new page in the documentation for the JSON.OBJLEN command.
While I was at it, I also fixed a few typos I found on the JSON.OBJKEYS page.
Ref: https://github.com/DiceDB/dice/issues/1282

Add documentation for JSON.OBJLEN command

---

internal/cli/cli.go

this is a config style optimize, nothing to do with core logic.
In config.go
there are some configs have  default value, such as  the following port **8082** and **8379**
`
type http struct {
Enabled bool `config:"enabled" default:"true"`
Port    int  `config:"port" default:"8082" validate:"number,gte=0,lte=65535"`
}
type websocket struct {
Enabled                 bool          `config:"enabled" default:"true"`
Port                    int           `config:"port" default:"8379" validate:"number,gte=0,lte=65535"`
MaxWriteResponseRetries int           `config:"max_write_response_retries" default:"3" validate:"min=0"`
WriteResponseTimeout    time.Duration `config:"write_response_timeout" default:"10s"`
}
`
but in cli.go the default value is not the same, such as  the following port **7380** …

fix: modify the config default value keep consistency

---

README.md
docs/src/content/docs/get-started/installation.mdx
docs/src/content/docs/get-started/reactive-hello-world.mdx

Issue
```
$ go run main.go --enable-multithreading --enable-watch
flag provided but not defined: -enable-multithreading
```
-enable-multithreading flag is removed.
https://github.com/DiceDB/dice/pull/1318/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17
`Multithreading is enabled by default`

Remove --enable-multithreading flag usage in README

---

integration_tests/commands/http/json_test.go
integration_tests/commands/resp/json_test.go
integration_tests/commands/websocket/json_test.go
internal/eval/eval_test.go
internal/eval/store_eval.go

This fixes the missing error message that happens when you run the `JSON.OBJLEN` command on a key that doesn't exist. (Presently, it returns a blank message.)
I discovered this inconsistency while [writing the `JSON.OBJLEN` page](https://github.com/DiceDB/dice/issues/1282).
Ref: #1353

Add error message for using JSON.OBJLEN on non-existant key

---

integration_tests/commands/http/hyperloglog_test.go
integration_tests/commands/websocket/hyperloglog_test.go
internal/cmd/cmds.go
internal/eval/commands.go
internal/eval/eval_test.go
internal/eval/execute.go
internal/eval/store_eval.go
internal/iothread/cmd_compose.go
internal/iothread/cmd_decompose.go
internal/iothread/cmd_meta.go
internal/iothread/cmd_preprocess.go
internal/iothread/iothread.go
internal/object/object.go

- Updated `PFMERGE` command to support as multishard command
- Added `preprocess`, `decompose`, `compose` implementation for `PFMERGE`
- Added unit tests
- Update integration tests (Disabled HTTP/WS tests as multishard command not supported for those)

Update `PFMERGE` to be supported as multishard command

---

internal/server/resp/server.go

Fixes #1398
Fixed format verb in  error wrapping in AcceptConnectionRequests method.

Fix format verb in  error wrapping in AcceptConnectionRequests method

---

config/validator.go
integration_tests/commands/http/json_test.go
internal/eval/commands.go
internal/eval/countminsketch.go
internal/eval/eval_test.go
internal/eval/store_eval.go

PR removes `validator` function fields in evalTestCase struct and all existing validators are moved to use `newValidator` func field.
Closes #1387

#1387: Remove validator field from evalTestCase.

---

docs/src/components/Nav.astro
docs/src/content/blog/dicedb-is-open-source.md
docs/src/styles/main.scss

update navbar styling, and fix broken links

---

examples/leaderboard-go/main.go

Update the leaderboard example to use ZRange.Watch instead of Q.Watch.
Issue : #1401

1401: Update leaderbard example to use zrange watch

---

internal/eval/countminsketch.go

Single matrix memory allocation in DeepCopy

---

docs/src/content/docs/commands/ZRANGE.md

Related to #1284
Add documentation for the `ZRANGE` command in DiceDB.
* Create a new file `docs/src/content/docs/commands/ZRANGE.md`.
* Add an introduction paragraph about the `ZRANGE` command.
* Include the syntax for the `ZRANGE` command.
* List all parameters the `ZRANGE` command accepts in a table.
* List all possible return values and under what condition in a table.
* Describe the behavior of the `ZRANGE` command.
* List all possible errors the `ZRANGE` command can throw and under what condition.
* Add examples of the `ZRANGE` command and the expected output.

Add documentation for ZRANGE command

---

internal/server/httpws/redisCmdAdapter.go
internal/server/httpws/redisCmdAdapter_test.go

fixes #1163
reference: https://pkg.go.dev/encoding/json#Decoder.UseNumber
> UseNumber causes the Decoder to unmarshal a number into an interface{} as a [Number](https://pkg.go.dev/encoding/json#Number) instead of as a float64.
- Use `json.Decoder` with `UseNumber` option to unmarshal the JSON object received from http handler.
- Added a testcase for `math.MinInt64`.
- Added testcases for errors.
SET
```
curl --location --request GET 'localhost:8082/set' \
--header 'Content-Type: application/json' \
--data '{
"key" : "a",
"value" : -9223372036854775808
}'
{"status":"success","data":"OK"}
```
GET
```
curl --location --request GET 'localhost:8082/get' \
--header 'Content-Type: application/json' \
--data '{
"key" : "a"
}'
{"status":"success","data":-9223372036854775808}
```

HTTP unmarshal a number into an interface{} as json.Number instead of float64

---

server/main.go

- Closes #1411 
**Description**
This PR sets password against an user when password is set with ```--password``` flag while starting the server with 
```go run main.go --password pass``` command.
<details>
<summary>Working Proof</summary>
- Starting the server with password flag
- Connecting cli and executing command without auth
- Auth with wrong password
- Auth with correct password
- Executing command with after successful auth
</details>

Fix: Ensure proper authentication when password is set against an user

---

docs/src/components/Footer.astro
docs/src/styles/main.scss

This PR fixes he GitHub icon misalignment issue in the footer on medium and small screens
-  Applied fit-content css property
-  Followed existing coding pattern
Issue Reference:
Closes #1436
Testing & Verification:
✅Verified the fix on screen dimensions 1025px, <768px and all others.
✅Ran golangci-lint and confirmed no linting errors.
Screenshots:

Icon alignment issue on Website

---

internal/cmd/cmd_del.go
internal/cmd/cmd_exists.go

This PR imports wire from correct package i.e. ```"github.com/dicedb/dicedb-go/wire"```

Import wire from correct package

---

internal/cmd/cmd_flushdb.go
internal/eval/commands.go
internal/eval/eval_test.go
internal/store/store.go

Migrate FLUSHDB command to support ironhawk engine.
fixes #1454

port FLUSHDB command to IronHawk

---

internal/server/ironhawk/iothread.go
internal/server/ironhawk/watch_manager.go

Closes #1478 
- When a new client connects it triggers message to all the connected/subscribed clients at that point of time.
- When a new client connects as part of `Subscribe()` when client sends `GET.WATCH` we're notifying all watchers.
- When a new client triggers `GET.WATCH` command we should just notify the client of the messages we've for that client if any pending don't need to trigger messages for all the subscribed clients, hence in notify watchers we're filtering the `GET.WATCH` command for given client if `GET.WATCH` subscribe.

Fix for repeat messages when new client connects

---

internal/cmd/cmd_decr.go
internal/cmd/cmd_decrby.go
internal/cmd/cmd_del.go
internal/cmd/cmd_exists.go
internal/cmd/cmd_expire.go
internal/cmd/cmd_expireat.go
internal/cmd/cmd_get.go
internal/cmd/cmd_incr.go
internal/cmd/cmd_incrby.go
internal/cmd/cmd_set.go
internal/cmd/cmd_ttl.go
internal/cmd/cmd_unwatch.go

Execute functions don't have length checks
DiceDB crashes if wrong number of args are given as it tries to get a shard for **args[0]**

Fix for ARGs length check

---

docs/src/content/docs/commands/EXPIRE.md

There is a typographical error in the documentation page for EXPIRE command. 
The word expiration is misspelled. This commit corrects the typographical error. 
Attached is the screenshot of the error located at https://dicedb.io/commands/expire/

Typo correction in Documentation - EXPIRE command page

---

Makefile

before change
Building for darwin/amd64
CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w -X config.DiceDBVersion=ERSION" -o ./dicedb
after change
Building for darwin/amd64
CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w -X config.DiceDBVersion=v1.0.3" -o ./dicedb

fix: VERSION Parameter not getting picked in make build 

---

internal/cmd/cmd_hget.go
internal/cmd/cmd_hgetall.go
internal/cmd/cmd_hgetall_watch.go
internal/cmd/cmd_hset.go
tests/commands/ironhawk/hget_test.go
tests/commands/ironhawk/hgetall_test.go
tests/commands/ironhawk/hset_test.go
tests/commands/ironhawk/main_test.go

Implements `HSET`, `HGET`, `HGETALL` commands on IronHawk and also adds support for watch subscription on `HGETALL`
Fixes: #1124

Adds support for `H*` command.

---

Makefile

Resolved an error in the Makefile that affected the build process. Updated the build step to ensure proper handling of the `$VERSION `variable
fixes https://github.com/DiceDB/dice/issues/1622

Fix: Makefile Build Error in DiceDB

---

docs/src/content/docs/commands/HANDSHAKE.md
internal/cmd/cmd_handshake.go

In PRs https://github.com/DiceDB/dice/pull/1580 and https://github.com/DiceDB/dice/pull/1582 the typo has been fixed only in docs/src/content/docs/commands/HANDSHAKE.md file. 
This PR aims to fix the typo in below files
docs/src/content/docs/commands/HANDSHAKE.md
internal/cmd/cmd_handshake.go

Fixed typo in HANDSHAKE.md and cmd_handshake.go

---

internal/cmd/cmd_get_watch.go
tests/commands/ironhawk/get_watch_test.go

Fix dice exit process on `GET.WATCH` with no arg.

---

internal/cmd/cmd_expireat.go
tests/commands/ironhawk/expireat_test.go

Implementing the TODO comment about checking for the upper bound of the input time for EXPIREAT
Test: Setting expire with more than 10 years timestamp vs setting with less than 10 years

FIRST PR: Add Upper Bound Check for EXPIREAT

---

internal/server/ironhawk/iothread.go

In case of an incorrect number of arguments for HANDSHAKE, an error is generated, but the server continues processing and does not return the error. Which results in a crash because it tries to get `Args[0]` & `Args[1]`

Bug Fix - Server crashes in case of wrong number of args

---

internal/server/ironhawk/iothread.go
internal/server/ironhawk/watch_manager.go

Making fingerprints of watchable commands and their `.WATCH` commands identical for easy detection in SDK

feat: Making fingerprints of watchable commands and their .WATCH commands identical

---

docs/src/content/docs/get-started/hello-world.mdx

fixes #1741
Note section of the commands breakdown is no longer valid as only single OK is returned for SET

FIX #1741 removed invalid Note section

---

Dockerfile
docker-compose.yml

- Bump Docker Go to 1.24.2
- Add Docker-compose configuration
The current golang version 1.24.1-alpine has [Vulnerabilities](https://hub.docker.com/layers/library/golang/1.24.1-alpine/images/sha256-ba0e119509b381457e9bb434319f2ef7996ad7ca7ec11a66e4ecdd8da49b8ddf), thus update to the latest version 1.24.2-alpine
Also added docker-compose.yml file

Update Golang Image version

---

internal/wal/wal_aof.go

1. Added missing buffer write logic after calculating checksum, size and payload
2. In the replay, fixed crc check only on the payload instead of full data
Evidence:
1. Ran set of commands that logged entries to segment wal file
2. Restarted to server to run Replay and connected client again to check whether db is loaded properly or not.

fix(wal): read-write logic

---

internal/wal/wal_forge.go

Addressing deadlocks in WAL forge implementation
